import type { CardId } from './cards';

export interface CardCopy {
  en: string;
  typeLabel: string;
  ability: string;
  /** One line, at most 15 Unicode characters including punctuation. */
  rule: string;
  /** One line, at most 15 Unicode characters including punctuation. */
  flavor: string;
}

export const CARD_COPY: Record<CardId, CardCopy> = {
  field_logistics: {
    en: 'FIELD LOGISTICS',
    typeLabel: '资源发展',
    ability: '后勤提速',
    rule: '回点提速，最多两级。',
    flavor: '粮草比口号管用。',
  },
  command_expansion: {
    en: 'COMMAND EXPANSION',
    typeLabel: '资源储备',
    ability: '扩容两点',
    rule: '上限增二，最多十四。',
    flavor: '指挥的人多了，听指挥的人少了。',
  },
  war_bonds: {
    en: 'WAR BONDS',
    typeLabel: '延迟收益',
    ability: '十八秒回款',
    rule: '付一返三，每局限两次。',
    flavor: '先欠账，后打仗。',
  },
  toxic_cloud: {
    en: 'TOXIC LOCKDOWN',
    typeLabel: '双向清场',
    ability: '三秒预警',
    rule: '八秒毒雾，双方步兵受伤。',
    flavor: '防毒面具按头发，毒气不按。',
  },
  smoke_withdrawal: {
    en: 'BREAK CONTACT',
    typeLabel: '撤离重整',
    ability: '烟幕断后',
    rule: '掩护后撤，到位恢复体力。',
    flavor: '烟一散，就知道谁没跑掉。',
  },
  reserve_mobilization: {
    en: 'CALL THE RESERVES',
    typeLabel: '延迟增援',
    ability: '重建防线',
    rule: '分批增援两队民兵并抽牌。',
    flavor: '新兵的爸爸也在名单里。',
  },
  fpv_drone: {
    en: 'FPV STRIKE DRONE',
    typeLabel: '一次性反甲',
    ability: '一费俯冲',
    rule: '航时二十四秒，撞击消耗。',
    flavor: '回收押金就别交了。',
  },
  air_assault: {
    en: 'AIR ASSAULT TEAM',
    typeLabel: '直升机机降',
    ability: '纵深投送',
    rule: '飞赴落点，索降五人后撤。',
    flavor: '说好的门到门呢。',
  },
  pickup: {
    en: 'MACHINE GUN TECHNICAL',
    typeLabel: '轻型车辆',
    ability: '机动压制',
    rule: '高速机枪车，怕反甲火力。',
    flavor: '车险那页早撕了。',
  },
  tow_ifv: {
    en: 'TOW MISSILE CARRIER',
    typeLabel: '反坦克战车',
    ability: '双武器协同',
    rule: '导弹猎甲，机枪独立压制。',
    flavor: '一枚导弹，全连三个月的饷。',
  },
  mortar_carrier: {
    en: 'MORTAR CARRIER',
    typeLabel: '机动炮兵',
    ability: '曲射转移',
    rule: '八秒曲射，近敌后撤转移。',
    flavor: '打完就跑，茶杯都不带洒的。',
  },
  recovery_vehicle: {
    en: 'ARMORED RECOVERY VEHICLE',
    typeLabel: '装甲后勤',
    ability: '前线抢修',
    rule: '停车修复附近一辆受损装甲。',
    flavor: '拖回坦克，拖不回人。',
  },
  command_vehicle: {
    en: 'FORWARD COMMAND VEHICLE',
    typeLabel: '指挥装甲',
    ability: '无线电协同',
    rule: '部署抽牌，持续支援附近步兵。',
    flavor: '天线最多的车，挨炮最早。',
  },
  mine_clearer: {
    en: 'ARMORED MINE CLEARER',
    typeLabel: '工程装甲',
    ability: '排雷开路',
    rule: '近距自动排雷，快速处理矮墙。',
    flavor: '他走过的路，别人才敢走。',
  },
  infantry: {
    en: 'RIFLE SQUAD',
    typeLabel: '步兵班组',
    ability: '班组凝聚',
    rule: '三人邻近，受击更稳。',
    flavor: '答到的声音一次比一次少。',
  },
  machinegun: {
    en: 'MACHINE GUN SQUAD',
    typeLabel: '机枪班组',
    ability: '步机协同',
    rule: '机枪对空，四名步枪护卫对地。',
    flavor: '子弹管够，阳寿另算。',
  },
  rocket: {
    en: 'ROCKET SQUAD',
    typeLabel: '火力支援',
    ability: '远距爆破',
    rule: '齐射后慢装填，可对空。',
    flavor: '尾焰比敌人先清场。',
  },
  tank: {
    en: 'MAIN BATTLE TANK',
    typeLabel: '主战坦克',
    ability: '双重火力',
    rule: '主炮四点八秒，同轴点射。',
    flavor: '外面打不穿，里面伸不直。',
  },
  helicopter: {
    en: 'ATTACK HELICOPTER',
    typeLabel: '武装直升机',
    ability: '六发扫射',
    rule: '连续六发，短停换弹。',
    flavor: '它一到，双方都找掩体。',
  },
  sniper: {
    en: 'SNIPER TEAM',
    typeLabel: '狙击小组',
    ability: '远距点射',
    rule: '点射步兵，对装甲伤害减半。',
    flavor: '枪声是给别人听的。',
  },
  medic: {
    en: 'COMBAT MEDICS',
    typeLabel: '战地医疗',
    ability: '低费救援',
    rule: '双人救治，优先抢救伤员。',
    flavor: '绷带比袜子还难找。',
  },
  mortar: {
    en: 'MORTAR TEAM',
    typeLabel: '迫击炮组',
    ability: '曲射压制',
    rule: '七秒曲射，近敌保持距离。',
    flavor: '炮弹飞一会儿，正好抽根烟。',
  },
  ifv: {
    en: 'INFANTRY FIGHTING VEHICLE',
    typeLabel: '步兵战车',
    ability: '机炮支援',
    rule: '快速机炮持续攻击地空目标。',
    flavor: '步兵的出租车，棺材的头等舱。',
  },
  morale: {
    en: 'MORALE BOOST',
    typeLabel: '战术指令',
    ability: '士气鼓舞',
    rule: '短时提升全军伤害与移速。',
    flavor: '演讲不挡子弹。',
  },
  artillery: {
    en: 'FIELD HOWITZER',
    typeLabel: '野战火炮',
    ability: '周期炮击',
    rule: '十二秒一发，观察后开火。',
    flavor: '按表开炮，按表收尸。',
  },
  supply: {
    en: 'FIELD RESUPPLY',
    typeLabel: '补给指令',
    ability: '战地补给',
    rule: '立即抽两张牌，手牌上限六张。',
    flavor: '这回罐头总该有开罐器了。',
  },
  jam: {
    en: 'SIGNAL JAMMING',
    typeLabel: '电子干扰',
    ability: '通讯封锁',
    rule: '九秒封锁敌方主动抽牌。',
    flavor: '终于没人下令送死了。',
  },
  overdraft: {
    en: 'OVERDRAFT',
    typeLabel: '资源爆发',
    ability: '透支指挥',
    rule: '立即+5指挥点，可破限。',
    flavor: '先花未来的军费。',
  },
  signal_jam: {
    en: 'SIGNAL JAM',
    typeLabel: '电子干扰',
    ability: '出牌封锁',
    rule: '敌方四秒无法出牌。',
    flavor: '电台里只剩雪花。',
  },
  airborne_insertion: {
    en: 'AIRBORNE INSERTION',
    typeLabel: '空降指令',
    ability: '敌后伞降',
    rule: '五人伞兵空降指定位置。',
    flavor: '纵深才是主场。',
  },
  forced_march: {
    en: 'FORCED MARCH',
    typeLabel: '机动指令',
    ability: '强行军',
    rule: '全军步兵提速35%。',
    flavor: '腿到用时方恨短。',
  },
  cyber_suppression: {
    en: 'CYBER SUPPRESSION',
    typeLabel: '电子干扰',
    ability: '经济压制',
    rule: '削敌3点，回点减半。',
    flavor: '炸的不是坦克，是工资单。',
  },
  smoke: {
    en: 'SMOKE SCREEN',
    typeLabel: '掩护指令',
    ability: '烟幕掩护',
    rule: '烟幕遮挡远距直射，不阻曲射。',
    flavor: '掩护了敌人，也掩护了自己。',
  },
  recon: {
    en: 'FIRE ADJUSTMENT',
    typeLabel: '侦察指令',
    ability: '侦察校射',
    rule: '短时提升全军射程并看穿烟幕。',
    flavor: '看清了，敌人也在吃罐头。',
  },
  flare: {
    en: 'ILLUMINATION FLARE',
    typeLabel: '侦察指令',
    ability: '照明弹',
    rule: '光照显形双方，烟幕仍挡直射。',
    flavor: '照亮敌人，也照亮自己。',
  },
  repair: {
    en: 'FIELD REPAIRS',
    typeLabel: '装甲后勤',
    ability: '战地抢修',
    rule: '单车立即抢修，再持续恢复。',
    flavor: '修得好坦克，修不好命。',
  },
  precision: {
    en: 'PRECISION HOWITZER',
    typeLabel: '校射火炮',
    ability: '观察校射',
    rule: '十五秒校射，打击重装。',
    flavor: '第一发问路，第二发要人。',
  },
  javelin: {
    en: 'JAVELIN TEAM',
    typeLabel: '制导反甲',
    ability: '专注反甲',
    rule: '重弹只打车，小枪近卫。',
    flavor: '锁定之后，坦克可以开始祷告了。',
  },
  anti_tank_gun: {
    en: 'TOWED ANTI-TANK GUN',
    typeLabel: '反坦克炮',
    ability: '阵地反甲',
    rule: '重炮只打车，小枪近卫。',
    flavor: '它和坦克，只能活一个。',
  },
  antitank_mine: {
    en: 'ANTI-TANK MINE',
    typeLabel: '地雷工事',
    ability: '装甲伏击',
    rule: '装甲触发，造成伤害与减速。',
    flavor: '埋的人自己都绕着走。',
  },
  aa_gun: {
    en: 'TWIN AA GUN',
    typeLabel: '固定防空',
    ability: '双联拦截',
    rule: '固定双联机炮，专门攻击空中。',
    flavor: '落下来的鸟粪不算战果。',
  },
  sam_vehicle: {
    en: 'RADAR SAM VEHICLE',
    typeLabel: '雷达防空',
    ability: '雷达追踪',
    rule: '雷达共享空情，导弹追踪防空。',
    flavor: '先确认那不是一群大雁。',
  },
  steadfast: {
    en: 'STEADFAST GUARD',
    typeLabel: '守备步兵',
    ability: '坚定守备',
    rule: '永不投降，仍会受伤或撤退。',
    flavor: '人可以倒，阵地不能。',
  },
  supply_team: {
    en: 'LOGISTICS LIAISON',
    typeLabel: '补给班组',
    ability: '部署补给',
    rule: '部署抽一张牌，提供较远视野。',
    flavor: '谁打补给车，谁今晚没饭。',
  },
  strike_jet: {
    en: 'GROUND-ATTACK JET',
    typeLabel: '对地航空',
    ability: '通场扫射',
    rule: '连续扫射，返航后低费再战。',
    flavor: '通场一次，花名册少一页。',
  },
  bomber: {
    en: 'TACTICAL BOMBER',
    typeLabel: '轰炸航空',
    ability: '通场投弹',
    rule: '六枚连投，返航后低费再战。',
    flavor: '炸弹不长眼，投弹手也不长。',
  },
  marines: {
    en: 'MARINES',
    typeLabel: '陆战步兵',
    ability: '战友整队',
    rule: '战友重伤，全班一次整队。',
    flavor: '登陆艇的舱门一开，没人回头。',
  },
  armed_police: {
    en: 'ARMED POLICE',
    typeLabel: '守备步兵',
    ability: '守备护卫',
    rule: '停步护卫邻近步兵。',
    flavor: '他们防的不是敌人，是逃兵。',
  },
  paratroopers: {
    en: 'PARATROOPERS',
    typeLabel: '轻装步兵',
    ability: '快速增援',
    rule: '入场短时加速，开火即止。',
    flavor: '落地先数人，再数敌人。',
  },
  rangers: {
    en: 'RANGERS',
    typeLabel: '侦察步兵',
    ability: '伏击首枪',
    rule: '停步蓄势，首枪克制步兵。',
    flavor: '等来的先是蚊子。',
  },
  militia: {
    en: 'MILITIA',
    typeLabel: '民兵班组',
    ability: '低费集结',
    rule: '低费集结，低士气易退易降。',
    flavor: '训练三天，子弹三发。',
  },
  assault: {
    en: 'ASSAULT INFANTRY',
    typeLabel: '突击步兵',
    ability: '接敌烟幕',
    rule: '近敌触发短烟与快速射击。',
    flavor: '冲进烟里之前，先写好家信。',
  },
  engineers: {
    en: 'COMBAT ENGINEERS',
    typeLabel: '工程步兵',
    ability: '破障拆墙',
    rule: '双人工具组，近身拆墙排雷。',
    flavor: '排雷这活，没有第二次。',
  },
  mountain: {
    en: 'MOUNTAIN INFANTRY',
    typeLabel: '山地步兵',
    ability: '掩体远射',
    rule: '稳据掩体，扩大射程。',
    flavor: '山上的人看山下，像看蚂蚁。',
  },
  scouts: {
    en: 'SCOUT MARKSMEN',
    typeLabel: '侦察射手',
    ability: '前沿观察',
    rule: '远距停步观察，微弱自卫。',
    flavor: '地图上的树又多了一棵。',
  },
  commandos: {
    en: 'COMMANDOS',
    typeLabel: '精锐步兵',
    ability: '精锐伏击',
    rule: '短时伏击，抗压不投降。',
    flavor: '精锐的战场，没有目击者。',
  },
  grenadiers: {
    en: 'GRENADIER TEAM',
    typeLabel: '榴弹班组',
    ability: '区域压制',
    rule: '榴弹压制地面，无法对空。',
    flavor: '扔远了炸敌人，扔近了炸自己。',
  },
  antiarmor: {
    en: 'ANTI-TANK TEAM',
    typeLabel: '反装甲兵',
    ability: '混编反甲',
    rule: 'RPG慢装填，步枪护卫。',
    flavor: '坦克最怕的不是坦克，是他们。',
  },
  manpads: {
    en: 'MANPADS TEAM',
    typeLabel: '便携防空',
    ability: '专职防空',
    rule: '制导导弹专门追击空中目标。',
    flavor: '一根管子，换一架飞机。',
  },
  heavy_mg: {
    en: 'HEAVY MACHINE GUN TEAM',
    typeLabel: '重机枪组',
    ability: '持续封锁',
    rule: '重机枪对空，两名步枪兵护卫。',
    flavor: '打得尽兴的人从来不搬弹箱。',
  },
  light_tank: {
    en: 'LIGHT TANK',
    typeLabel: '轻型装甲',
    ability: '机动炮击',
    rule: '主炮三点八秒，机动支援。',
    flavor: '速度是它唯一的装甲。',
  },
  heavy_tank: {
    en: 'HEAVY ASSAULT TANK',
    typeLabel: '重型装甲',
    ability: '重装突破',
    rule: '主炮六点四秒，近卫点射。',
    flavor: '它碾过的地方，不用挖战壕了。',
  },
  rocket_heli: {
    en: 'ANTI-ARMOR HELICOPTER',
    typeLabel: '反甲直升机',
    ability: '导弹猎甲',
    rule: '四点二秒制导打击载具。',
    flavor: '坦克最怕的声音，从头顶来。',
  },
  scout_drone: {
    en: 'RECON QUADCOPTER',
    typeLabel: '侦察无人机',
    ability: '前线观察',
    rule: '助邻近友军增程并穿烟瞄准。',
    flavor: '电池比情报先耗尽。',
  },
  attack_drone: {
    en: 'ARMED UAV',
    typeLabel: '察打无人机',
    ability: '通场反甲',
    rule: '单次反甲，返航整备后低费再战。',
    flavor: '飞行员在一千公里外喝咖啡。',
  },
  loiter_drone: {
    en: 'LOITERING MUNITION',
    typeLabel: '巡飞弹药',
    ability: '俯冲突击',
    rule: '优先俯冲装甲，自毁范围爆炸。',
    flavor: '它不回来，也不需要回来。',
  },
  interceptor: {
    en: 'INTERCEPTOR',
    typeLabel: '制空航空',
    ability: '前沿巡逻',
    rule: '巡逻二十四秒，返航一费。',
    flavor: '跑道尽头，咖啡永远喝不完。',
  },
  rally: {
    en: 'EMERGENCY RALLY',
    typeLabel: '动员指令',
    ability: '稳住阵脚',
    rule: '一费回士气，清除大幅压制。',
    flavor: '收拢的人里，总有几个不该在的。',
  },
  ammo: {
    en: 'AMMUNITION AIRDROP',
    typeLabel: '空投补给',
    ability: '空投弹药',
    rule: '立即抽三张牌，手牌上限六张。',
    flavor: '弹药箱落地，战争暂停十秒。',
  },
  emp: {
    en: 'ELECTROMAGNETIC BLOCKADE',
    typeLabel: '电子战术',
    ability: '电磁封锁',
    rule: '空中制导停火，封锁抽牌。',
    flavor: '屏幕一黑，战争回到二战。',
  },
  barrage: {
    en: 'HEAVY HOWITZER',
    typeLabel: '重型火炮',
    ability: '重炮覆盖',
    rule: '十七秒重炮，覆盖落点。',
    flavor: '一轮弹幕，山头矮了三米。',
  },
  medevac: {
    en: 'FIELD FIRST AID',
    typeLabel: '急救指令',
    ability: '战地急救',
    rule: '救起伤员，治疗周围步兵。',
    flavor: '能上飞机的，都还有救。',
  },
  fortify: {
    en: 'HOLD THE LINE',
    typeLabel: '防御指令',
    ability: '固守阵地',
    rule: '静止减伤三成，持续十秒。',
    flavor: '工事修得越好，越舍不得走。',
  },
  sabotage: {
    en: 'FIRE DISRUPTION',
    typeLabel: '干扰指令',
    ability: '延迟装填',
    rule: '已见敌军停火三秒。',
    flavor: '敌人的炮弹，永远晚一秒。',
  },
  war_production: {
    en: 'WAR PRODUCTION',
    typeLabel: '爆发经济',
    ability: '战时生产',
    rule: '即得两点，回点提速四成。',
    flavor: '造坦克的速度，比埋人快。',
  },
  foraged_supplies: {
    en: 'FORAGED SUPPLIES',
    typeLabel: '低费过牌',
    ability: '就地补给',
    rule: '支付一点，立即抽两张。',
    flavor: '缴获的罐头最香。',
  },
  blitz_doctrine: {
    en: 'BLITZ DOCTRINE',
    typeLabel: '全军机动',
    ability: '闪电战',
    rule: '步兵移速提升四成五。',
    flavor: '等他们挖好，已经绕后了。',
  },
  forward_hq: {
    en: 'FORWARD HQ',
    typeLabel: '永久提速',
    ability: '前沿指挥部',
    rule: '回点提速，上限减二。',
    flavor: '指挥部离前线越近，离后方越远。',
  },
  comm_blackout: {
    en: 'COMM BLACKOUT',
    typeLabel: '经济封锁',
    ability: '通讯中断',
    rule: '敌方八秒停止回点。',
    flavor: '命令靠传令兵，传令兵靠运气。',
  },
  supply_interdiction: {
    en: 'SUPPLY INTERDICTION',
    typeLabel: '费用封锁',
    ability: '补给拦截',
    rule: '敌方三张牌费用加二。',
    flavor: '半路少一箱是一箱。',
  },
  spoof_attack: {
    en: 'SPOOF ATTACK',
    typeLabel: '阵型扰乱',
    ability: '佯攻',
    rule: '敌方步兵转向三秒。',
    flavor: '假情报比真子弹快。',
  },
  radar_jam: {
    en: 'RADAR JAM',
    typeLabel: '反空反导',
    ability: '雷达干扰',
    rule: '敌方空袭精度大降。',
    flavor: '屏幕上全是鸟群。',
  },
  glider_assault: {
    en: 'GLIDER ASSAULT',
    typeLabel: '精英空降',
    ability: '滑翔机突击',
    rule: '四精英静默空降伏击。',
    flavor: '没有引擎声的来客。',
  },
  pathfinders: {
    en: 'PATHFINDERS',
    typeLabel: '侦察空降',
    ability: '先导小组',
    rule: '两人空降，超远视野。',
    flavor: '他们落地的时候，援军还在天上。',
  },
  ambush_squad: {
    en: 'AMBUSH SQUAD',
    typeLabel: '守备伏击',
    ability: '伏击小组',
    rule: '静止两秒，首射翻倍。',
    flavor: '他们等的人，从来没等到他们。',
  },
  sniper_team: {
    en: 'SNIPER TEAM',
    typeLabel: '远距点杀',
    ability: '狙击小组',
    rule: '射程八百八，优先步兵。',
    flavor: '两个人，一颗子弹，一条命。',
  },
  veteran_squad: {
    en: 'VETERAN SQUAD',
    typeLabel: '精锐主力',
    ability: '老兵班组',
    rule: '六老兵，高纪律抗压制。',
    flavor: '伤疤就是资历章。',
  },
  medic_team: {
    en: 'MEDIC TEAM',
    typeLabel: '持续救治',
    ability: '医疗小组',
    rule: '三军医，治疗量提升。',
    flavor: '绷带管够，血不够。',
  },
  combat_engineers: {
    en: 'COMBAT ENGINEERS',
    typeLabel: '攻坚破障',
    ability: '战斗工兵',
    rule: '爆破矮墙，清除地雷。',
    flavor: '桥是工兵修的，命是坦克的。',
  },
  naval_gunfire: {
    en: 'NAVAL GUNFIRE',
    typeLabel: '重型舰炮',
    ability: '舰炮支援',
    rule: '三点四秒后重炮一发。',
    flavor: '海平线上的问候。',
  },
  cluster_munitions: {
    en: 'CLUSTER MUNITIONS',
    typeLabel: '区域覆盖',
    ability: '集束弹药',
    rule: '八发子弹药连续覆盖。',
    flavor: '天上下的是铁豌豆。',
  },
  thermobaric: {
    en: 'THERMOBARIC',
    typeLabel: '温压灼烧',
    ability: '温压弹',
    rule: '大范围高温灼烧。',
    flavor: '它烧完空气，人自己倒下。',
  },
  precision_rocket: {
    en: 'PRECISION ROCKET',
    typeLabel: '精确点杀',
    ability: '精确火箭',
    rule: '两秒后火箭精准命中。',
    flavor: '误差按厘米算，账单按百万算。',
  },
  entrench: {
    en: 'ENTRENCH',
    typeLabel: '守备减伤',
    ability: '掘壕固守',
    rule: '全军卧倒，减伤三成。',
    flavor: '挖得越深，离地狱越近。',
  },
  // ── v120 新卡 ────────────────────────────────────────────────────
  command_lockdown: {
    en: 'COMMAND LOCKDOWN',
    typeLabel: '电子干扰',
    ability: '出牌封锁',
    rule: '敌方三秒无法出牌。',
    flavor: '敌人的命令，卡在嗓子里。',
  },
  emergency_levy: {
    en: 'EMERGENCY LEVY',
    typeLabel: '资源爆发',
    ability: '紧急征发',
    rule: '立即+3指挥点，回点放缓。',
    flavor: '连炊事班都发枪了。',
  },
  battlefield_salvage: {
    en: 'BATTLEFIELD SALVAGE',
    typeLabel: '资源循环',
    ability: '战场回收',
    rule: '抽回弃牌堆低费单位。',
    flavor: '敌人的零件也是零件。',
  },
  shock_action: {
    en: 'SHOCK ACTION',
    typeLabel: '步兵压制',
    ability: '震慑行动',
    rule: '敌步兵压制并定身。',
    flavor: '炮火把勇气，炸成了本能。',
  },
  sensor_blind: {
    en: 'SENSOR BLIND',
    typeLabel: '电子干扰',
    ability: '视野压制',
    rule: '敌方视野骤降六秒。',
    flavor: '致盲之后，敌人靠猜打仗。',
  },
  logistics_strike: {
    en: 'LOGISTICS STRIKE',
    typeLabel: '资源打击',
    ability: '后勤斩首',
    rule: '削敌三点指挥点。',
    flavor: '后勤一断，坦克变碉堡。',
  },
  freq_hop: {
    en: 'FREQUENCY HOPPING',
    typeLabel: '电子反制',
    ability: '跳频通讯',
    rule: '八秒内免疫敌方干扰。',
    flavor: '频道跳得快，命令丢得快。',
  },
  ewarfare: {
    en: 'EW SUPPRESSION',
    typeLabel: '电子干扰',
    ability: '电子压制',
    rule: '敌方回点放缓五秒。',
    flavor: '看不见的战争，电台先阵亡。',
  },
  airborne_at: {
    en: 'AIRBORNE AT TEAM',
    typeLabel: '空降反甲',
    ability: '敌后伞降',
    rule: '四人伞降反甲班。',
    flavor: '坦克的后方，从来不安全。',
  },
  rapid_insertion: {
    en: 'RAPID INSERTION',
    typeLabel: '空降穿插',
    ability: '高速穿插',
    rule: '三人高速空降穿插。',
    flavor: '他们的退路，是自己打出来的。',
  },
  sapper_assault: {
    en: 'ASSAULT SAPPERS',
    typeLabel: '破障突击',
    ability: '突击工兵',
    rule: '四人工兵，减伤五成。',
    flavor: '雷场的缺口，是工兵拿命换的。',
  },
  recon_jump: {
    en: 'RECON JUMP',
    typeLabel: '空降侦察',
    ability: '侦察跳降',
    rule: '双人空降前沿侦察。',
    flavor: '先落地的先看见明天。',
  },
  creeping_barrage: {
    en: 'CREEPING BARRAGE',
    typeLabel: '徐进弹幕',
    ability: '递进覆盖',
    rule: '六发弹幕逐次延伸。',
    flavor: '跟着炮弹冲锋，慢一步就死。',
  },
  smoke_cover: {
    en: 'SMOKE COVER',
    typeLabel: '宽幅烟幕',
    ability: '烟幕急袭',
    rule: '三道烟幕宽幅遮蔽。',
    flavor: '整条街都消失了。',
  },
  heavy_barrage: {
    en: 'HEAVY BARRAGE',
    typeLabel: '重型打击',
    ability: '重型弹幕',
    rule: '四发重炮大范围打击。',
    flavor: '一轮重炮，阵地变成月球。',
  },
  illumination_round: {
    en: 'ILLUMINATION ROUND',
    typeLabel: '持久照明',
    ability: '照明弹',
    rule: '目标区域照明十四秒。',
    flavor: '黑夜变白昼，偷袭变明攻。',
  },
  minefield: {
    en: 'MIXED MINEFIELD',
    typeLabel: '区域封锁',
    ability: '混合雷场',
    rule: '三颗反甲雷成片布置。',
    flavor: '整条路都不欢迎坦克。',
  },
  field_hospital: {
    en: 'FIELD HOSPITAL',
    typeLabel: '持续治疗',
    ability: '野战医院',
    rule: '三军医，治疗量提升。',
    flavor: '能自己走的，优先。',
  },
  fallback: {
    en: 'TACTICAL FALLBACK',
    typeLabel: '战术撤退',
    ability: '战术后撤',
    rule: '全军步兵快速后撤。',
    flavor: '保存自己才能消灭敌人。',
  },
  fire_team: {
    en: 'FIRE TEAM',
    typeLabel: '轻装步兵',
    ability: '火力小组',
    rule: '双人轻装步兵班。',
    flavor: '人少，但来得快。',
  },
  assault_grenadiers: {
    en: 'ASSAULT GRENADIERS',
    typeLabel: '手雷突击',
    ability: '突击掷弹兵',
    rule: '四人掷弹班，近战专精。',
    flavor: '拉环声最提神。',
  },
  lmg_team: {
    en: 'LMG TEAM',
    typeLabel: '机动压制',
    ability: '轻机枪组',
    rule: '双人机枪，可对空。',
    flavor: '枪管换得比水勤。',
  },
};
