import type { CardId } from './cards';

export interface CardCopy {
  en: string;
  typeLabel: string;
  ability: string;
  /** One line, at most 15 Unicode characters including punctuation. */
  rule: string;
  /** One line, at most 15 Unicode characters including punctuation. */
  flavor: string;
}

export const CARD_COPY: Record<CardId, CardCopy> = {
  field_logistics: {
    en: 'FIELD LOGISTICS',
    typeLabel: '资源发展',
    ability: '后勤提速',
    rule: '回点提速，最多两级。',
    flavor: '粮草比口号管用。',
  },
  command_expansion: {
    en: 'COMMAND EXPANSION',
    typeLabel: '资源储备',
    ability: '扩容两点',
    rule: '上限增二，最多十四。',
    flavor: '桌子大了，账也多了。',
  },
  war_bonds: {
    en: 'WAR BONDS',
    typeLabel: '延迟收益',
    ability: '十八秒回款',
    rule: '付一返三，每局限两次。',
    flavor: '先欠账，后打仗。',
  },
  toxic_cloud: {
    en: 'TOXIC LOCKDOWN',
    typeLabel: '双向清场',
    ability: '三秒预警',
    rule: '八秒毒雾，双方步兵受伤。',
    flavor: '风向可不认军衔。',
  },
  smoke_withdrawal: {
    en: 'BREAK CONTACT',
    typeLabel: '撤离重整',
    ability: '烟幕断后',
    rule: '掩护后撤，到位恢复体力。',
    flavor: '晚饭改到后面吃。',
  },
  reserve_mobilization: {
    en: 'CALL THE RESERVES',
    typeLabel: '延迟增援',
    ability: '重建防线',
    rule: '分批增援两队民兵并抽牌。',
    flavor: '靴子还没穿热。',
  },
  fpv_drone: {
    en: 'FPV STRIKE DRONE',
    typeLabel: '一次性反甲',
    ability: '一费俯冲',
    rule: '航时二十四秒，撞击消耗。',
    flavor: '回收押金就别交了。',
  },
  air_assault: {
    en: 'AIR ASSAULT TEAM',
    typeLabel: '直升机机降',
    ability: '纵深投送',
    rule: '飞赴落点，索降五人后撤。',
    flavor: '说好的门到门呢。',
  },
  pickup: {
    en: 'MACHINE GUN TECHNICAL',
    typeLabel: '轻型车辆',
    ability: '机动压制',
    rule: '高速机枪车，怕反甲火力。',
    flavor: '车险那页早撕了。',
  },
  tow_ifv: {
    en: 'TOW MISSILE CARRIER',
    typeLabel: '反坦克战车',
    ability: '双武器协同',
    rule: '导弹猎甲，机枪独立压制。',
    flavor: '停车费比导弹便宜。',
  },
  mortar_carrier: {
    en: 'MORTAR CARRIER',
    typeLabel: '机动炮兵',
    ability: '曲射转移',
    rule: '八秒曲射，近敌后撤转移。',
    flavor: '刚摆好茶杯又要挪窝。',
  },
  recovery_vehicle: {
    en: 'ARMORED RECOVERY VEHICLE',
    typeLabel: '装甲后勤',
    ability: '前线抢修',
    rule: '停车修复附近一辆受损装甲。',
    flavor: '扳手比配枪用得勤。',
  },
  command_vehicle: {
    en: 'FORWARD COMMAND VEHICLE',
    typeLabel: '指挥装甲',
    ability: '无线电协同',
    rule: '部署抽牌，持续支援附近步兵。',
    flavor: '车里永远有人抢麦。',
  },
  mine_clearer: {
    en: 'ARMORED MINE CLEARER',
    typeLabel: '工程装甲',
    ability: '排雷开路',
    rule: '近距自动排雷，快速处理矮墙。',
    flavor: '今天又得第一个走。',
  },
  infantry: {
    en: 'RIFLE SQUAD',
    typeLabel: '步兵班组',
    ability: '班组凝聚',
    rule: '三人邻近，受击更稳。',
    flavor: '点名时总有人答两遍。',
  },
  machinegun: {
    en: 'MACHINE GUN SQUAD',
    typeLabel: '机枪班组',
    ability: '步机协同',
    rule: '机枪对空，四名步枪护卫对地。',
    flavor: '擦枪时最想念的是打枪。',
  },
  rocket: {
    en: 'ROCKET SQUAD',
    typeLabel: '火力支援',
    ability: '远距爆破',
    rule: '齐射后慢装填，可对空。',
    flavor: '耳塞又忘在另一件衣服里。',
  },
  tank: {
    en: 'MAIN BATTLE TANK',
    typeLabel: '主战坦克',
    ability: '双重火力',
    rule: '主炮四点八秒，同轴点射。',
    flavor: '装甲很厚，腿还是伸不开。',
  },
  helicopter: {
    en: 'ATTACK HELICOPTER',
    typeLabel: '武装直升机',
    ability: '六发扫射',
    rule: '连续六发，短停换弹。',
    flavor: '先把被吹跑的地图捡回来。',
  },
  sniper: {
    en: 'SNIPER TEAM',
    typeLabel: '狙击小组',
    ability: '远距点射',
    rule: '点射步兵，对装甲伤害减半。',
    flavor: '谁带了驱蚊水？',
  },
  medic: {
    en: 'COMBAT MEDICS',
    typeLabel: '战地医疗',
    ability: '低费救援',
    rule: '双人救治，优先抢救伤员。',
    flavor: '绷带比袜子还难找。',
  },
  mortar: {
    en: 'MORTAR TEAM',
    typeLabel: '迫击炮组',
    ability: '曲射压制',
    rule: '七秒曲射，近敌保持距离。',
    flavor: '今天的风不按课本吹。',
  },
  ifv: {
    en: 'INFANTRY FIGHTING VEHICLE',
    typeLabel: '步兵战车',
    ability: '机炮支援',
    rule: '快速机炮持续攻击地空目标。',
    flavor: '进车前先商量谁的膝盖归谁。',
  },
  morale: {
    en: 'MORALE BOOST',
    typeLabel: '战术指令',
    ability: '士气鼓舞',
    rule: '短时提升全军伤害与移速。',
    flavor: '长官说完，饭还是凉的。',
  },
  artillery: {
    en: 'FIELD HOWITZER',
    typeLabel: '野战火炮',
    ability: '周期炮击',
    rule: '十二秒一发，观察后开火。',
    flavor: '装填手听不得别人劝他健身。',
  },
  supply: {
    en: 'FIELD RESUPPLY',
    typeLabel: '补给指令',
    ability: '战地补给',
    rule: '立即抽两张牌，手牌上限六张。',
    flavor: '这回罐头总该有开罐器了。',
  },
  jam: {
    en: 'SIGNAL JAMMING',
    typeLabel: '电子干扰',
    ability: '通讯封锁',
    rule: '九秒封锁敌方主动抽牌。',
    flavor: '终于不用听长官试麦了。',
  },
  overdraft: {
    en: 'OVERDRAFT',
    typeLabel: '资源爆发',
    ability: '透支指挥',
    rule: '立即+5指挥点，可破限。',
    flavor: '先花未来的军费。',
  },
  signal_jam: {
    en: 'SIGNAL JAM',
    typeLabel: '电子干扰',
    ability: '出牌封锁',
    rule: '敌方四秒无法出牌。',
    flavor: '电台里只剩雪花。',
  },
  airborne_insertion: {
    en: 'AIRBORNE INSERTION',
    typeLabel: '空降指令',
    ability: '敌后伞降',
    rule: '五人伞兵空降指定位置。',
    flavor: '纵深才是主场。',
  },
  forced_march: {
    en: 'FORCED MARCH',
    typeLabel: '机动指令',
    ability: '强行军',
    rule: '全军步兵提速35%。',
    flavor: '腿到用时方恨短。',
  },
  cyber_suppression: {
    en: 'CYBER SUPPRESSION',
    typeLabel: '电子干扰',
    ability: '经济压制',
    rule: '削敌3点，回点减半。',
    flavor: '让对手的账本归零。',
  },
  smoke: {
    en: 'SMOKE SCREEN',
    typeLabel: '掩护指令',
    ability: '烟幕掩护',
    rule: '烟幕遮挡远距直射，不阻曲射。',
    flavor: '班长也不知道队伍走哪了。',
  },
  recon: {
    en: 'FIRE ADJUSTMENT',
    typeLabel: '侦察指令',
    ability: '侦察校射',
    rule: '短时提升全军射程并看穿烟幕。',
    flavor: '看清了，敌人也在吃罐头。',
  },
  flare: {
    en: 'ILLUMINATION FLARE',
    typeLabel: '侦察指令',
    ability: '照明弹',
    rule: '光照显形双方，烟幕仍挡直射。',
    flavor: '半夜开了灯，谁也别想摸黑。',
  },
  repair: {
    en: 'FIELD REPAIRS',
    typeLabel: '装甲后勤',
    ability: '战地抢修',
    rule: '单车立即抢修，再持续恢复。',
    flavor: '地上又多一颗螺丝。',
  },
  precision: {
    en: 'PRECISION HOWITZER',
    typeLabel: '校射火炮',
    ability: '观察校射',
    rule: '十五秒校射，打击重装。',
    flavor: '地图上的油渍不算坐标。',
  },
  javelin: {
    en: 'JAVELIN TEAM',
    typeLabel: '制导反甲',
    ability: '专注反甲',
    rule: '重弹只打车，小枪近卫。',
    flavor: '先别锁定，电池还在充。',
  },
  anti_tank_gun: {
    en: 'TOWED ANTI-TANK GUN',
    typeLabel: '反坦克炮',
    ability: '阵地反甲',
    rule: '重炮只打车，小枪近卫。',
    flavor: '转炮靠人，谁又说想健身？',
  },
  antitank_mine: {
    en: 'ANTI-TANK MINE',
    typeLabel: '地雷工事',
    ability: '装甲伏击',
    rule: '装甲触发，造成伤害与减速。',
    flavor: '地雷埋哪了？地图在洗衣房。',
  },
  aa_gun: {
    en: 'TWIN AA GUN',
    typeLabel: '固定防空',
    ability: '双联拦截',
    rule: '固定双联机炮，专门攻击空中。',
    flavor: '落下来的鸟粪不算战果。',
  },
  sam_vehicle: {
    en: 'RADAR SAM VEHICLE',
    typeLabel: '雷达防空',
    ability: '雷达追踪',
    rule: '雷达共享空情，导弹追踪防空。',
    flavor: '先确认那不是一群大雁。',
  },
  steadfast: {
    en: 'STEADFAST GUARD',
    typeLabel: '守备步兵',
    ability: '坚定守备',
    rule: '永不投降，仍会受伤或撤退。',
    flavor: '班长连打瞌睡都不肯挪窝。',
  },
  supply_team: {
    en: 'LOGISTICS LIAISON',
    typeLabel: '补给班组',
    ability: '部署补给',
    rule: '部署抽一张牌，提供较远视野。',
    flavor: '一到饭点就成了全团熟人。',
  },
  strike_jet: {
    en: 'GROUND-ATTACK JET',
    typeLabel: '对地航空',
    ability: '通场扫射',
    rule: '连续扫射，返航后低费再战。',
    flavor: '摄影师只拍到半截尾巴。',
  },
  bomber: {
    en: 'TACTICAL BOMBER',
    typeLabel: '轰炸航空',
    ability: '通场投弹',
    rule: '六枚连投，返航后低费再战。',
    flavor: '炸弹投完了，早餐还没消化。',
  },
  marines: {
    en: 'MARINES',
    typeLabel: '陆战步兵',
    ability: '战友整队',
    rule: '战友重伤，全班一次整队。',
    flavor: '袜子湿了，队伍没散。',
  },
  armed_police: {
    en: 'ARMED POLICE',
    typeLabel: '守备步兵',
    ability: '守备护卫',
    rule: '停步护卫邻近步兵。',
    flavor: '门岗的凳子又被借走了。',
  },
  paratroopers: {
    en: 'PARATROOPERS',
    typeLabel: '轻装步兵',
    ability: '快速增援',
    rule: '入场短时加速，开火即止。',
    flavor: '落地第一件事是找队友。',
  },
  rangers: {
    en: 'RANGERS',
    typeLabel: '侦察步兵',
    ability: '伏击首枪',
    rule: '停步蓄势，首枪克制步兵。',
    flavor: '等来的先是蚊子。',
  },
  militia: {
    en: 'MILITIA',
    typeLabel: '民兵班组',
    ability: '低费集结',
    rule: '低费集结，低士气易退易降。',
    flavor: '枪领到了，背带拿鞋绳凑。',
  },
  assault: {
    en: 'ASSAULT INFANTRY',
    typeLabel: '突击步兵',
    ability: '接敌烟幕',
    rule: '近敌触发短烟与快速射击。',
    flavor: '烟散了才发现帽子戴反。',
  },
  engineers: {
    en: 'COMBAT ENGINEERS',
    typeLabel: '工程步兵',
    ability: '破障排雷',
    rule: '双人拆墙，近身排雷。',
    flavor: '扳手又进了谁的饭盒。',
  },
  mountain: {
    en: 'MOUNTAIN INFANTRY',
    typeLabel: '山地步兵',
    ability: '掩体远射',
    rule: '稳据掩体，扩大射程。',
    flavor: '水壶又比人先下山。',
  },
  scouts: {
    en: 'SCOUT MARKSMEN',
    typeLabel: '侦察射手',
    ability: '前沿观察',
    rule: '远距停步观察，微弱自卫。',
    flavor: '地图上的树又多了一棵。',
  },
  commandos: {
    en: 'COMMANDOS',
    typeLabel: '精锐步兵',
    ability: '精锐伏击',
    rule: '短时伏击，抗压不投降。',
    flavor: '暗号差点说成早餐。',
  },
  grenadiers: {
    en: 'GRENADIER TEAM',
    typeLabel: '榴弹班组',
    ability: '区域压制',
    rule: '榴弹压制地面，无法对空。',
    flavor: '扔石头也得先报个距离。',
  },
  antiarmor: {
    en: 'ANTI-TANK TEAM',
    typeLabel: '反装甲兵',
    ability: '混编反甲',
    rule: 'RPG慢装填，步枪护卫。',
    flavor: '弹筒占了午饭的位置。',
  },
  manpads: {
    en: 'MANPADS TEAM',
    typeLabel: '便携防空',
    ability: '专职防空',
    rule: '制导导弹专门追击空中目标。',
    flavor: '防空值班最先酸的是脖子。',
  },
  heavy_mg: {
    en: 'HEAVY MACHINE GUN TEAM',
    typeLabel: '重机枪组',
    ability: '持续封锁',
    rule: '重机枪对空，两名步枪兵护卫。',
    flavor: '打得尽兴的人从来不搬弹箱。',
  },
  light_tank: {
    en: 'LIGHT TANK',
    typeLabel: '轻型装甲',
    ability: '机动炮击',
    rule: '主炮三点八秒，机动支援。',
    flavor: '转弯慢点，茶缸没焊上。',
  },
  heavy_tank: {
    en: 'HEAVY ASSAULT TANK',
    typeLabel: '重型装甲',
    ability: '重装突破',
    rule: '主炮六点四秒，近卫点射。',
    flavor: '发动前先把加油车叫来。',
  },
  rocket_heli: {
    en: 'ANTI-ARMOR HELICOPTER',
    typeLabel: '反甲直升机',
    ability: '导弹猎甲',
    rule: '四点二秒制导打击载具。',
    flavor: '导弹挂满了，饭盒只能抱着。',
  },
  scout_drone: {
    en: 'RECON QUADCOPTER',
    typeLabel: '侦察无人机',
    ability: '前线观察',
    rule: '助邻近友军增程并穿烟瞄准。',
    flavor: '别催，遥控器又没电了。',
  },
  attack_drone: {
    en: 'ARMED UAV',
    typeLabel: '察打无人机',
    ability: '通场反甲',
    rule: '单次反甲，返航整备后低费再战。',
    flavor: '飞行员还穿着拖鞋。',
  },
  loiter_drone: {
    en: 'LOITERING MUNITION',
    typeLabel: '巡飞弹药',
    ability: '俯冲突击',
    rule: '优先俯冲装甲，自毁范围爆炸。',
    flavor: '保养手册只有起飞前那页。',
  },
  interceptor: {
    en: 'INTERCEPTOR',
    typeLabel: '制空航空',
    ability: '前沿巡逻',
    rule: '巡逻二十四秒，返航一费。',
    flavor: '起飞太急，咖啡还在梯子上。',
  },
  rally: {
    en: 'EMERGENCY RALLY',
    typeLabel: '动员指令',
    ability: '稳住阵脚',
    rule: '一费回士气，清除大幅压制。',
    flavor: '哈欠终于对齐了。',
  },
  ammo: {
    en: 'AMMUNITION AIRDROP',
    typeLabel: '空投补给',
    ability: '空投弹药',
    rule: '立即抽三张牌，手牌上限六张。',
    flavor: '收货的人又得先爬树。',
  },
  emp: {
    en: 'ELECTROMAGNETIC BLOCKADE',
    typeLabel: '电子战术',
    ability: '电磁封锁',
    rule: '空中制导停火，封锁抽牌。',
    flavor: '连闹钟也安静了。',
  },
  barrage: {
    en: 'HEAVY HOWITZER',
    typeLabel: '重型火炮',
    ability: '重炮覆盖',
    rule: '十七秒重炮，覆盖落点。',
    flavor: '打完这轮，茶里又多一层土。',
  },
  medevac: {
    en: 'FIELD FIRST AID',
    typeLabel: '急救指令',
    ability: '战地急救',
    rule: '救起伤员，治疗周围步兵。',
    flavor: '军医午觉也得排班。',
  },
  fortify: {
    en: 'HOLD THE LINE',
    typeLabel: '防御指令',
    ability: '固守阵地',
    rule: '静止减伤三成，持续十秒。',
    flavor: '沙袋垒好了，门也堵了。',
  },
  sabotage: {
    en: 'FIRE DISRUPTION',
    typeLabel: '干扰指令',
    ability: '延迟装填',
    rule: '已见敌军停火三秒。',
    flavor: '卡壳声比集合哨清醒。',
  },
  war_production: {
    en: 'WAR PRODUCTION',
    typeLabel: '爆发经济',
    ability: '战时生产',
    rule: '即得两点，回点提速四成。',
    flavor: '烟囱比炮声先响。',
  },
  foraged_supplies: {
    en: 'FORAGED SUPPLIES',
    typeLabel: '低费过牌',
    ability: '就地补给',
    rule: '支付一点，立即抽两张。',
    flavor: '缴获的罐头最香。',
  },
  blitz_doctrine: {
    en: 'BLITZ DOCTRINE',
    typeLabel: '全军机动',
    ability: '闪电战',
    rule: '步兵移速提升四成五。',
    flavor: '别等他们挖好坑。',
  },
  forward_hq: {
    en: 'FORWARD HQ',
    typeLabel: '永久提速',
    ability: '前沿指挥部',
    rule: '回点提速，上限减二。',
    flavor: '桌子搬到前线了。',
  },
  comm_blackout: {
    en: 'COMM BLACKOUT',
    typeLabel: '经济封锁',
    ability: '通讯中断',
    rule: '敌方八秒停止回点。',
    flavor: '电台里只剩雪花。',
  },
  supply_interdiction: {
    en: 'SUPPLY INTERDICTION',
    typeLabel: '费用封锁',
    ability: '补给拦截',
    rule: '敌方三张牌费用加二。',
    flavor: '半路少一箱是一箱。',
  },
  spoof_attack: {
    en: 'SPOOF ATTACK',
    typeLabel: '阵型扰乱',
    ability: '佯攻',
    rule: '敌方步兵转向三秒。',
    flavor: '假情报比真子弹快。',
  },
  radar_jam: {
    en: 'RADAR JAM',
    typeLabel: '反空反导',
    ability: '雷达干扰',
    rule: '敌方空袭精度大降。',
    flavor: '屏幕上全是鸟群。',
  },
  glider_assault: {
    en: 'GLIDER ASSAULT',
    typeLabel: '精英空降',
    ability: '滑翔机突击',
    rule: '四精英静默空降伏击。',
    flavor: '没有引擎声的来客。',
  },
  pathfinders: {
    en: 'PATHFINDERS',
    typeLabel: '侦察空降',
    ability: '先导小组',
    rule: '两人空降，超远视野。',
    flavor: '先到的人画地图。',
  },
  ambush_squad: {
    en: 'AMBUSH SQUAD',
    typeLabel: '守备伏击',
    ability: '伏击小组',
    rule: '静止两秒，首射翻倍。',
    flavor: '草丛里有人数呼吸。',
  },
  sniper_team: {
    en: 'SNIPER TEAM',
    typeLabel: '远距点杀',
    ability: '狙击小组',
    rule: '射程八百八，优先步兵。',
    flavor: '枪声从两公里外来。',
  },
  veteran_squad: {
    en: 'VETERAN SQUAD',
    typeLabel: '精锐主力',
    ability: '老兵班组',
    rule: '六老兵，高纪律抗压制。',
    flavor: '伤疤就是资历章。',
  },
  medic_team: {
    en: 'MEDIC TEAM',
    typeLabel: '持续救治',
    ability: '医疗小组',
    rule: '三军医，治疗量提升。',
    flavor: '绷带永远不够用。',
  },
  combat_engineers: {
    en: 'COMBAT ENGINEERS',
    typeLabel: '攻坚破障',
    ability: '战斗工兵',
    rule: '爆破矮墙，清除地雷。',
    flavor: '钳子和炸药都熟。',
  },
  naval_gunfire: {
    en: 'NAVAL GUNFIRE',
    typeLabel: '重型舰炮',
    ability: '舰炮支援',
    rule: '三点四秒后重炮一发。',
    flavor: '海平线上的问候。',
  },
  cluster_munitions: {
    en: 'CLUSTER MUNITIONS',
    typeLabel: '区域覆盖',
    ability: '集束弹药',
    rule: '八发子弹药连续覆盖。',
    flavor: '天上下的是铁豌豆。',
  },
  thermobaric: {
    en: 'THERMOBARIC',
    typeLabel: '温压灼烧',
    ability: '温压弹',
    rule: '大范围高温灼烧。',
    flavor: '空气自己烧起来。',
  },
  precision_rocket: {
    en: 'PRECISION ROCKET',
    typeLabel: '精确点杀',
    ability: '精确火箭',
    rule: '两秒后火箭精准命中。',
    flavor: '误差按厘米算。',
  },
  entrench: {
    en: 'ENTRENCH',
    typeLabel: '守备减伤',
    ability: '掘壕固守',
    rule: '全军卧倒，减伤三成。',
    flavor: '铲子是第二件武器。',
  },
};
