import type { CardId } from './cards';

export interface CardCopy {
  en: string;
  typeLabel: string;
  ability: string;
  /** One line, at most 15 Unicode characters including punctuation. */
  rule: string;
  /** One line, at most 15 Unicode characters including punctuation. */
  flavor: string;
}

export const CARD_COPY: Record<CardId, CardCopy> = {
  infantry: {
    en: 'RIFLE SQUAD',
    typeLabel: '步兵班组',
    ability: '快速推进',
    rule: '六人低费班组，独立推进。',
    flavor: '海报上的靴子从来不沾泥。',
  },
  machinegun: {
    en: 'MACHINE GUN SQUAD',
    typeLabel: '机枪班组',
    ability: '步机协同',
    rule: '机枪对空，四名步枪护卫对地。',
    flavor: '擦枪时最想念的是打枪。',
  },
  rocket: {
    en: 'ROCKET SQUAD',
    typeLabel: '火力支援',
    ability: '远距爆破',
    rule: '火箭对地对空，可破坏地形。',
    flavor: '耳塞又忘在另一件衣服里。',
  },
  tank: {
    en: 'MAIN BATTLE TANK',
    typeLabel: '主战坦克',
    ability: '双重火力',
    rule: '主炮换弹，同轴机枪独立射击。',
    flavor: '装甲很厚，腿还是伸不开。',
  },
  helicopter: {
    en: 'ATTACK HELICOPTER',
    typeLabel: '武装直升机',
    ability: '空中支援',
    rule: '空中推进，持续攻击地面目标。',
    flavor: '先把被吹跑的地图捡回来。',
  },
  sniper: {
    en: 'SNIPER TEAM',
    typeLabel: '狙击小组',
    ability: '远距点射',
    rule: '点射步兵，对装甲伤害减半。',
    flavor: '谁带了驱蚊水？',
  },
  medic: {
    en: 'COMBAT MEDICS',
    typeLabel: '战地医疗',
    ability: '优先救治',
    rule: '治疗步兵，优先救助倒地伤员。',
    flavor: '连他的饭盒都被拿去消毒了。',
  },
  mortar: {
    en: 'MORTAR TEAM',
    typeLabel: '迫击炮组',
    ability: '曲射压制',
    rule: '曲射压制，敌军逼近时后撤。',
    flavor: '今天的风不按课本吹。',
  },
  ifv: {
    en: 'INFANTRY FIGHTING VEHICLE',
    typeLabel: '步兵战车',
    ability: '机炮支援',
    rule: '快速机炮持续攻击地空目标。',
    flavor: '进车前先商量谁的膝盖归谁。',
  },
  morale: {
    en: 'MORALE BOOST',
    typeLabel: '战术指令',
    ability: '士气鼓舞',
    rule: '短时提升全军伤害与移速。',
    flavor: '长官说完，饭还是凉的。',
  },
  artillery: {
    en: 'FIELD HOWITZER',
    typeLabel: '野战火炮',
    ability: '周期炮击',
    rule: '周期炮击友军已发现的目标。',
    flavor: '装填手听不得别人劝他健身。',
  },
  supply: {
    en: 'FIELD RESUPPLY',
    typeLabel: '补给指令',
    ability: '战地补给',
    rule: '立即抽两张牌，手牌上限六张。',
    flavor: '这回罐头总该有开罐器了。',
  },
  jam: {
    en: 'SIGNAL JAMMING',
    typeLabel: '电子干扰',
    ability: '通讯封锁',
    rule: '九秒封锁敌方主动抽牌。',
    flavor: '终于不用听长官试麦了。',
  },
  smoke: {
    en: 'SMOKE SCREEN',
    typeLabel: '掩护指令',
    ability: '烟幕掩护',
    rule: '烟幕遮挡远距直射，不阻曲射。',
    flavor: '班长也不知道队伍走哪了。',
  },
  recon: {
    en: 'FIRE ADJUSTMENT',
    typeLabel: '侦察指令',
    ability: '侦察校射',
    rule: '短时提升全军射程并看穿烟幕。',
    flavor: '看清了，敌人也在吃罐头。',
  },
  repair: {
    en: 'FIELD REPAIRS',
    typeLabel: '装甲后勤',
    ability: '战地抢修',
    rule: '持续修复已在场的存活装甲。',
    flavor: '修完了，地上还剩一颗螺丝。',
  },
  precision: {
    en: 'PRECISION HOWITZER',
    typeLabel: '校射火炮',
    ability: '观察校射',
    rule: '依靠友军观察，低频校射炮击。',
    flavor: '地图上的油渍不算坐标。',
  },
  javelin: {
    en: 'JAVELIN TEAM',
    typeLabel: '制导反甲',
    ability: '制导追踪',
    rule: '高抛制导打装甲，对步兵弱。',
    flavor: '先别锁定，电池还在充。',
  },
  anti_tank_gun: {
    en: 'TOWED ANTI-TANK GUN',
    typeLabel: '反坦克炮',
    ability: '阵地穿甲',
    rule: '固定远距反甲，近处存在盲区。',
    flavor: '转炮靠人，谁又说想健身？',
  },
  antitank_mine: {
    en: 'ANTI-TANK MINE',
    typeLabel: '地雷工事',
    ability: '装甲伏击',
    rule: '装甲触发，造成伤害与减速。',
    flavor: '地雷埋哪了？地图在洗衣房。',
  },
  aa_gun: {
    en: 'TWIN AA GUN',
    typeLabel: '固定防空',
    ability: '双联拦截',
    rule: '固定双联机炮，专门攻击空中。',
    flavor: '落下来的鸟粪不算战果。',
  },
  sam_vehicle: {
    en: 'RADAR SAM VEHICLE',
    typeLabel: '雷达防空',
    ability: '雷达追踪',
    rule: '雷达共享空情，导弹追踪防空。',
    flavor: '先确认那不是一群大雁。',
  },
  steadfast: {
    en: 'STEADFAST GUARD',
    typeLabel: '守备步兵',
    ability: '坚定守备',
    rule: '永不投降，仍会受伤或撤退。',
    flavor: '班长连打瞌睡都不肯挪窝。',
  },
  supply_team: {
    en: 'LOGISTICS LIAISON',
    typeLabel: '补给班组',
    ability: '部署补给',
    rule: '部署抽一张牌，提供较远视野。',
    flavor: '一到饭点就成了全团熟人。',
  },
  strike_jet: {
    en: 'GROUND-ATTACK JET',
    typeLabel: '对地航空',
    ability: '通场扫射',
    rule: '单次扫射，返航整备后低费再战。',
    flavor: '摄影师只拍到半截尾巴。',
  },
  bomber: {
    en: 'TACTICAL BOMBER',
    typeLabel: '轰炸航空',
    ability: '通场投弹',
    rule: '单次投弹，返航整备后低费再战。',
    flavor: '炸弹投完了，早餐还没消化。',
  },
  marines: {
    en: 'MARINES',
    typeLabel: '陆战步兵',
    ability: '交替突击',
    rule: '交替掩护推进，近距火力增强。',
    flavor: '招募海报上没画湿袜子。',
  },
  armed_police: {
    en: 'ARMED POLICE',
    typeLabel: '守备步兵',
    ability: '防护背心',
    rule: '背心降低伤害，低姿态守备。',
    flavor: '挠个痒还得先卸背心。',
  },
  paratroopers: {
    en: 'PARATROOPERS',
    typeLabel: '轻装步兵',
    ability: '轻装前出',
    rule: '轻装快速推进，交替突击前出。',
    flavor: '今天又是走着去的。',
  },
  rangers: {
    en: 'RANGERS',
    typeLabel: '侦察步兵',
    ability: '掩体机动',
    rule: '低姿态侦察，寻找更远的掩体。',
    flavor: '班长的捷径总要多翻一座山。',
  },
  militia: {
    en: 'MILITIA',
    typeLabel: '民兵班组',
    ability: '低费集结',
    rule: '低费集结，低士气易退易降。',
    flavor: '枪领到了，背带拿鞋绳凑。',
  },
  assault: {
    en: 'ASSAULT INFANTRY',
    typeLabel: '突击步兵',
    ability: '近距强攻',
    rule: '短程强攻，近距离额外增伤。',
    flavor: '踹门练熟了，宿舍门没了。',
  },
  engineers: {
    en: 'COMBAT ENGINEERS',
    typeLabel: '工程步兵',
    ability: '障碍爆破',
    rule: '接近矮墙时爆破，拆除障碍。',
    flavor: '这墙看着像我们上周砌的。',
  },
  mountain: {
    en: 'MOUNTAIN INFANTRY',
    typeLabel: '山地步兵',
    ability: '越障攀登',
    rule: '低姿态掩护，更快攀墙脱坑。',
    flavor: '又得去捡滚下山的水壶。',
  },
  scouts: {
    en: 'SCOUT MARKSMEN',
    typeLabel: '侦察射手',
    ability: '快速点射',
    rule: '快速点射，对装甲伤害减半。',
    flavor: '侦察完回来，多了两只蜱虫。',
  },
  commandos: {
    en: 'COMMANDOS',
    typeLabel: '精锐步兵',
    ability: '精锐突击',
    rule: '高士气抗压制，成员交替突击。',
    flavor: '潜行考试栽在一声喷嚏上。',
  },
  grenadiers: {
    en: 'GRENADIER TEAM',
    typeLabel: '榴弹班组',
    ability: '区域压制',
    rule: '榴弹压制地面，无法对空。',
    flavor: '扔石头也得先报个距离。',
  },
  antiarmor: {
    en: 'ANTI-TANK TEAM',
    typeLabel: '反装甲兵',
    ability: '远距伏击',
    rule: '远距反甲增伤，无法对空。',
    flavor: '蹲了一上午，先等来送饭的。',
  },
  manpads: {
    en: 'MANPADS TEAM',
    typeLabel: '便携防空',
    ability: '专职防空',
    rule: '制导导弹专门追击空中目标。',
    flavor: '防空值班最先酸的是脖子。',
  },
  heavy_mg: {
    en: 'HEAVY MACHINE GUN TEAM',
    typeLabel: '重机枪组',
    ability: '持续封锁',
    rule: '重机枪对空，两名步枪兵护卫。',
    flavor: '打得尽兴的人从来不搬弹箱。',
  },
  light_tank: {
    en: 'LIGHT TANK',
    typeLabel: '轻型装甲',
    ability: '机动炮击',
    rule: '快速机动，主炮机枪独立射击。',
    flavor: '转弯慢点，茶缸没焊上。',
  },
  heavy_tank: {
    en: 'HEAVY ASSAULT TANK',
    typeLabel: '重型装甲',
    ability: '重装突破',
    rule: '重甲慢行，主炮机枪独立射击。',
    flavor: '发动前先把加油车叫来。',
  },
  rocket_heli: {
    en: 'ANTI-ARMOR HELICOPTER',
    typeLabel: '反甲直升机',
    ability: '导弹猎甲',
    rule: '空中追踪反甲，无法对空。',
    flavor: '导弹挂满了，饭盒只能抱着。',
  },
  scout_drone: {
    en: 'RECON QUADCOPTER',
    typeLabel: '侦察无人机',
    ability: '前线观察',
    rule: '助邻近友军增程并穿烟瞄准。',
    flavor: '别催，遥控器又没电了。',
  },
  attack_drone: {
    en: 'ARMED UAV',
    typeLabel: '察打无人机',
    ability: '通场反甲',
    rule: '单次反甲，返航整备后低费再战。',
    flavor: '飞行员还穿着拖鞋。',
  },
  loiter_drone: {
    en: 'LOITERING MUNITION',
    typeLabel: '巡飞弹药',
    ability: '俯冲突击',
    rule: '优先俯冲装甲，自毁范围爆炸。',
    flavor: '保养手册只有起飞前那页。',
  },
  interceptor: {
    en: 'INTERCEPTOR',
    typeLabel: '制空航空',
    ability: '高速拦截',
    rule: '单次防空，返航整备后低费再战。',
    flavor: '起飞太急，咖啡还在梯子上。',
  },
  rally: {
    en: 'EMERGENCY RALLY',
    typeLabel: '动员指令',
    ability: '稳住阵脚',
    rule: '步兵恢复士气，大幅清除压制。',
    flavor: '全班的哈欠终于对齐了。',
  },
  ammo: {
    en: 'AMMUNITION AIRDROP',
    typeLabel: '空投补给',
    ability: '空投弹药',
    rule: '立即抽三张牌，手牌上限六张。',
    flavor: '收货的人又得先爬树。',
  },
  emp: {
    en: 'ELECTROMAGNETIC BLOCKADE',
    typeLabel: '电子战术',
    ability: '电磁封锁',
    rule: '封锁主动抽牌，取消敌方侦察。',
    flavor: '连班长的闹钟也安静了。',
  },
  barrage: {
    en: 'HEAVY HOWITZER',
    typeLabel: '重型火炮',
    ability: '重炮覆盖',
    rule: '周期重炮轰击已发现目标。',
    flavor: '打完这轮，茶里又多一层土。',
  },
  medevac: {
    en: 'FIELD FIRST AID',
    typeLabel: '急救指令',
    ability: '战地急救',
    rule: '步兵回血恢复士气，救起伤员。',
    flavor: '军医连午觉都得排班。',
  },
  fortify: {
    en: 'HOLD THE LINE',
    typeLabel: '防御指令',
    ability: '固守阵地',
    rule: '静止步兵短时减伤并恢复士气。',
    flavor: '沙袋垒好了，门也堵住了。',
  },
  sabotage: {
    en: 'FIRE DISRUPTION',
    typeLabel: '干扰指令',
    ability: '延迟装填',
    rule: '延后敌军主武器与机枪装填。',
    flavor: '卡壳声比集合哨还让人清醒。',
  },
};
