import type { CardId } from './cards';

export const DECK_PRESETS: {
  id: string;
  name: string;
  plan: string;
  cards: CardId[];
}[] = [
  {
    id: 'combined',
    name: '机步协同',
    plan: '步兵护卫皮卡，陶式猎甲；抢修延长装甲作战时间。',
    cards: [
      'scouts',
      'medic',
      'engineers',
      'militia',
      'infantry',
      'infantry',
      'antiarmor',
      'antiarmor',
      'machinegun',
      'manpads',
      'pickup',
      'pickup',
      'tow_ifv',
      'recovery_vehicle',
      'tank',
      'supply',
      'supply',
      'repair',
      'recon',
      'morale',
    ],
  },
  {
    id: 'assault',
    name: '烟幕突击',
    plan: '先用烟幕缩短暴露距离，陆战队与突击组接敌后再鼓舞。',
    cards: [
      'scouts',
      'militia',
      'engineers',
      'medic',
      'infantry',
      'infantry',
      'marines',
      'marines',
      'assault',
      'assault',
      'antiarmor',
      'antiarmor',
      'manpads',
      'pickup',
      'command_vehicle',
      'smoke',
      'smoke',
      'rally',
      'supply',
      'morale',
    ],
  },
  {
    id: 'fire_support',
    name: '守备炮兵',
    plan: '侦察提供炮击目标，武警和混编反甲班守住炮兵前方。',
    cards: [
      'scouts',
      'scouts',
      'armed_police',
      'armed_police',
      'steadfast',
      'machinegun',
      'antiarmor',
      'antiarmor',
      'manpads',
      'scout_drone',
      'artillery',
      'precision',
      'mortar_carrier',
      'command_vehicle',
      'mine_clearer',
      'fortify',
      'recon',
      'supply',
      'medevac',
      'sabotage',
    ],
  },
  {
    id: 'air_mobile',
    name: '空地快援',
    plan: '轻装稳线，机降绕后；FPV猎甲，飞机按已发现的目标出动。',
    cards: [
      'scouts',
      'medic',
      'militia',
      'infantry',
      'infantry',
      'antiarmor',
      'antiarmor',
      'heavy_mg',
      'manpads',
      'scout_drone',
      'air_assault',
      'light_tank',
      'strike_jet',
      'fpv_drone',
      'interceptor',
      'smoke',
      'recon',
      'emp',
      'supply',
      'supply',
    ],
  },
];
