import type { CardId } from './cards';

export const DECK_PRESETS: {
  id: string;
  name: string;
  plan: string;
  cards: CardId[];
}[] = [
  {
    id: 'combined',
    name: '机步协同',
    plan: '基础班组掩护装甲推进，工兵破障、轻机枪伴随，标枪与防空留作反制。',
    cards: [
      'infantry',
      'infantry',
      'infantry',
      'fire_team',
      'antiarmor',
      'antiarmor',
      'javelin',
      'manpads',
      'sam_vehicle',
      'supply',
      'supply',
      'supply_team',
      'medic',
      'tank',
      'tow_ifv',
      'command_expansion',
      'scout_car',
      'flame_tank',
      'infantry',
      'smoke_withdrawal',
    ],
  },
  {
    id: 'assault',
    name: '烟幕突击',
    plan: '烟幕缩短暴露距离，掷弹兵与陆战队接敌，震慑行动钉死敌方步兵。',
    cards: [
      'infantry',
      'infantry',
      'sapper_assault',
      'marines',
      'marines',
      'assault',
      'assault_grenadiers',
      'flame_team',
      'antiarmor',
      'antiarmor',
      'manpads',
      'sam_vehicle',
      'supply',
      'supply',
      'supply_team',
      'javelin',
      'flame_tank',
      'smoke',
      'morale',
      'shock_action',
    ],
  },
  {
    id: 'fire_support',
    name: '守备炮兵',
    plan: '侦察提供炮击目标，徐进弹幕与重型弹幕逐步吞噬敌方防线。',
    cards: [
      'infantry',
      'infantry',
      'infantry',
      'antiarmor',
      'antiarmor',
      'javelin',
      'manpads',
      'sam_vehicle',
      'supply',
      'supply',
      'supply_team',
      'recon',
      'mortar_carrier',
      'artillery',
      'mlrs',
      'light_mortar',
      'scout_car',
      'creeping_barrage',
      'heavy_barrage',
      'fortify',
    ],
  },
  {
    id: 'air_mobile',
    name: '空地快援',
    plan: '轻装稳线，空降反甲与穿插班直插敌后；FPV猎甲，飞机按已发现目标出动。',
    cards: [
      'infantry',
      'infantry',
      'infantry',
      'paratroopers',
      'airborne_at',
      'rapid_insertion',
      'recon_jump',
      'antiarmor',
      'antiarmor',
      'sam_vehicle',
      'interceptor',
      'supply',
      'supply',
      'supply_team',
      'scouts',
      'air_assault',
      'strike_jet',
      'fpv_drone',
      'signal_jam',
      'emp',
    ],
  },
  {
    id: 'counterattack',
    name: '纵深反击',
    plan: '雷场迟滞敌方冲锋，战术后撤保存有生力量，延迟援兵重建防线。',
    cards: [
      'infantry',
      'infantry',
      'militia',
      'antiarmor',
      'antiarmor',
      'javelin',
      'manpads',
      'sam_vehicle',
      'medic',
      'field_hospital',
      'supply',
      'supply',
      'machinegun',
      'scouts',
      'toxic_cloud',
      'smoke_withdrawal',
      'reserve_mobilization',
      'reserve_mobilization',
      'minefield',
      'fallback',
    ],
  },
  {
    id: 'blitz',
    name: '透支快攻',
    plan: '透支与紧急征发瞬间铺场，强行军贴脸；指挥静默封住对手反扑，廉价班组源源不断。',
    cards: [
      'infantry',
      'infantry',
      'infantry',
      'fire_team',
      'fire_team',
      'militia',
      'assault',
      'marines',
      'flame_team',
      'supply',
      'antiarmor',
      'javelin',
      'manpads',
      'overdraft',
      'overdraft',
      'emergency_levy',
      'emergency_levy',
      'forced_march',
      'command_lockdown',
      'shock_action',
    ],
  },
  {
    id: 'lockdown',
    name: '电磁封锁',
    plan: '用干扰和电子压制掐断对手指挥点与视野，稳守防线慢慢磨死对方。',
    cards: [
      'infantry',
      'infantry',
      'infantry',
      'militia',
      'antiarmor',
      'antiarmor',
      'javelin',
      'manpads',
      'sam_vehicle',
      'machinegun',
      'fortify',
      'supply',
      'supply',
      'supply_team',
      'scouts',
      'signal_jam',
      'command_lockdown',
      'sensor_blind',
      'logistics_strike',
      'ewarfare',
    ],
  },
];

// Independent opponent plans retain each style and use the same card rules.
export const AI_DECKS: CardId[][] = [
  // 机步协同
  [
    'infantry',
    'infantry',
    'infantry',
    'fire_team',
    'antiarmor',
    'infantry',
    'command_expansion',
    'javelin',
    'manpads',
    'sam_vehicle',
    'supply',
    'supply',
    'supply_team',
    'medic',
    'tank',
    'tow_ifv',
    'lmg_team',
    'scout_car',
    'flame_tank',
    'smoke_withdrawal',
  ],
  // 烟幕突击
  [
    'infantry',
    'infantry',
    'sapper_assault',
    'marines',
    'marines',
    'assault',
    'assault_grenadiers',
    'flame_team',
    'antiarmor',
    'manpads',
    'sam_vehicle',
    'supply',
    'supply',
    'supply_team',
    'scouts',
    'javelin',
    'flame_tank',
    'smoke',
    'morale',
    'shock_action',
  ],
  // 守备炮兵
  [
    'infantry',
    'infantry',
    'infantry',
    'antiarmor',
    'antiarmor',
    'javelin',
    'manpads',
    'sam_vehicle',
    'supply',
    'supply',
    'supply_team',
    'recon',
    'mortar_carrier',
    'artillery',
    'mlrs',
    'light_mortar',
    'scout_car',
    'creeping_barrage',
    'heavy_barrage',
    'fortify',
  ],
  // 空地快援
  [
    'infantry',
    'infantry',
    'infantry',
    'paratroopers',
    'airborne_at',
    'rapid_insertion',
    'recon_jump',
    'antiarmor',
    'antiarmor',
    'sam_vehicle',
    'interceptor',
    'supply',
    'supply',
    'supply_team',
    'scouts',
    'air_assault',
    'strike_jet',
    'fpv_drone',
    'signal_jam',
    'emp',
  ],
  // 纵深反击
  [
    'infantry',
    'infantry',
    'militia',
    'antiarmor',
    'antiarmor',
    'javelin',
    'manpads',
    'sam_vehicle',
    'medic',
    'field_hospital',
    'supply',
    'supply',
    'machinegun',
    'scouts',
    'toxic_cloud',
    'smoke_withdrawal',
    'reserve_mobilization',
    'reserve_mobilization',
    'minefield',
    'fallback',
  ],
  // 透支快攻
  [
    'infantry',
    'infantry',
    'infantry',
    'fire_team',
    'fire_team',
    'militia',
    'assault',
    'marines',
    'flame_team',
    'supply',
    'antiarmor',
    'javelin',
    'manpads',
    'overdraft',
    'forced_march',
    'emergency_levy',
    'emergency_levy',
    'command_lockdown',
    'shock_action',
    'battlefield_salvage',
  ],
  // 电磁封锁
  [
    'infantry',
    'infantry',
    'infantry',
    'militia',
    'antiarmor',
    'antiarmor',
    'manpads',
    'sam_vehicle',
    'machinegun',
    'fortify',
    'supply',
    'supply',
    'supply_team',
    'scouts',
    'signal_jam',
    'command_lockdown',
    'sensor_blind',
    'logistics_strike',
    'ewarfare',
    'freq_hop',
  ],
];
