import type { CardId } from './cards';

export const DECK_PRESETS: {
  id: string;
  name: string;
  plan: string;
  cards: CardId[];
}[] = [
  {
    id: 'combined',
    name: '机步协同',
    plan: '基础班组掩护装甲推进，标枪与防空留作反制。',
    cards: [
      'infantry',
      'infantry',
      'infantry',
      'infantry',
      'militia',
      'antiarmor',
      'antiarmor',
      'javelin',
      'manpads',
      'sam_vehicle',
      'supply',
      'supply',
      'supply_team',
      'scouts',
      'medic',
      'tank',
      'pickup',
      'tow_ifv',
      'smoke_withdrawal',
      'recon',
    ],
  },
  {
    id: 'assault',
    name: '烟幕突击',
    plan: '先用烟幕缩短暴露距离，陆战队与突击组接敌后再鼓舞。',
    cards: [
      'infantry',
      'infantry',
      'infantry',
      'militia',
      'marines',
      'marines',
      'assault',
      'antiarmor',
      'antiarmor',
      'manpads',
      'sam_vehicle',
      'supply',
      'supply',
      'supply_team',
      'javelin',
      'medic',
      'machinegun',
      'smoke',
      'infantry',
      'morale',
    ],
  },
  {
    id: 'fire_support',
    name: '守备炮兵',
    plan: '侦察提供炮击目标，武警和混编反甲班守住炮兵前方。',
    cards: [
      'infantry',
      'infantry',
      'infantry',
      'armed_police',
      'antiarmor',
      'antiarmor',
      'javelin',
      'manpads',
      'sam_vehicle',
      'supply',
      'supply',
      'supply_team',
      'scouts',
      'medic',
      'mortar_carrier',
      'artillery',
      'machinegun',
      'fortify',
      'infantry',
      'recon',
    ],
  },
  {
    id: 'air_mobile',
    name: '空地快援',
    plan: '轻装稳线，机降绕后；FPV猎甲，飞机按已发现的目标出动。',
    cards: [
      'infantry',
      'infantry',
      'infantry',
      'militia',
      'paratroopers',
      'antiarmor',
      'antiarmor',
      'sam_vehicle',
      'interceptor',
      'supply',
      'supply',
      'supply_team',
      'scouts',
      'medic',
      'air_assault',
      'strike_jet',
      'fpv_drone',
      'fpv_drone',
      'emp',
      'recon',
    ],
  },
  {
    id: 'counterattack',
    name: '纵深反击',
    plan: '保留撤收与清场指令，用延迟援兵重建防线；防空反甲守住空窗。',
    cards: [
      'infantry',
      'infantry',
      'militia',
      'militia',
      'antiarmor',
      'antiarmor',
      'javelin',
      'manpads',
      'sam_vehicle',
      'medic',
      'medic',
      'supply',
      'supply',
      'machinegun',
      'scouts',
      'toxic_cloud',
      'smoke_withdrawal',
      'reserve_mobilization',
      'reserve_mobilization',
      'fpv_drone',
    ],
  },
];

// Independent opponent plans retain each style and use the same card rules.
export const AI_DECKS: CardId[][] = [
  // 机步协同
  [
    'infantry',
    'infantry',
    'infantry',
    'infantry',
    'militia',
    'antiarmor',
    'machinegun',
    'javelin',
    'manpads',
    'sam_vehicle',
    'supply',
    'supply',
    'supply_team',
    'scouts',
    'medic',
    'tank',
    'pickup',
    'tow_ifv',
    'smoke_withdrawal',
    'recon',
  ],
  // 烟幕突击
  [
    'infantry',
    'infantry',
    'infantry',
    'militia',
    'marines',
    'marines',
    'assault',
    'antiarmor',
    'javelin',
    'manpads',
    'sam_vehicle',
    'supply',
    'supply',
    'scouts',
    'javelin',
    'medic',
    'machinegun',
    'smoke',
    'infantry',
    'morale',
  ],
  // 守备炮兵
  [
    'infantry',
    'infantry',
    'infantry',
    'armed_police',
    'antiarmor',
    'militia',
    'javelin',
    'manpads',
    'sam_vehicle',
    'supply',
    'supply',
    'javelin',
    'scouts',
    'medic',
    'mortar_carrier',
    'artillery',
    'machinegun',
    'fortify',
    'infantry',
    'recon',
  ],
  // 空地快援
  [
    'infantry',
    'infantry',
    'infantry',
    'militia',
    'paratroopers',
    'antiarmor',
    'javelin',
    'sam_vehicle',
    'interceptor',
    'supply',
    'supply',
    'infantry',
    'scouts',
    'medic',
    'air_assault',
    'strike_jet',
    'fpv_drone',
    'machinegun',
    'emp',
    'recon',
  ],
  // 纵深反击
  [
    'infantry',
    'infantry',
    'militia',
    'militia',
    'antiarmor',
    'antiarmor',
    'javelin',
    'manpads',
    'sam_vehicle',
    'medic',
    'infantry',
    'supply',
    'supply',
    'machinegun',
    'scouts',
    'toxic_cloud',
    'smoke_withdrawal',
    'reserve_mobilization',
    'javelin',
    'fpv_drone',
  ],
];
