import {emplacementContact} from '../game/emplacement-ground';
import {drawArticulatedGun} from '../game/gun-art';
import {gunMount} from '../game/gun-geometry';
import '../app/globals.css';
import {createRoot} from 'react-dom/client';import {CardFace} from '../game/card-art';
import {GUN_IDS_V227,EXPANSION_IDS_V227} from '../game/expansion-v227';
import {loadBattleArt} from '../game/art';import {createGame,startGame,spawnUnit,tick,refreshVision,CARDS,type GameState,type CardId} from '../game/engine';import {render} from '../game/render';
import {createScenery} from '../game/world';
import {advanceBattleFrame} from '../game/battle-clock';import {BattleFrameBudget} from '../game/battle-frame-budget';
const ids:CardId[]=[...EXPANSION_IDS_V227,'pickup','supply_truck','apc_transport','mlrs'];
createRoot(document.querySelector('#cards')!).render(ids.map(id=><div className="card-preview" key={id}><CardFace id={id} eager/></div>));
const select=document.getElementById('unit') as unknown as HTMLSelectElement;select.innerHTML=ids.map(id=>`<option value="${id}">${CARDS[id].name}</option>`).join('');
const canvas=document.querySelector<HTMLCanvasElement>('#view')!,ctx=canvas.getContext('2d')!,stats=document.querySelector('#stats')!,art=await loadBattleArt('greyline');
const gallery=document.querySelector('#gun-gallery')!;
const samples=GUN_IDS_V227.map(id=>{const cell=document.createElement('div'),label=document.createElement('p'),canvas=document.createElement('canvas');canvas.width=420;canvas.height=170;cell.style.background='#344035';label.textContent=CARDS[id].name;cell.appendChild(label);cell.appendChild(canvas);gallery.appendChild(cell);return {id,canvas,label};});
let gunLevel=0,gunAnimation=false,gunDirection=1,gunFiredAt=-100;
document.querySelector('#gun-low')!.addEventListener('click',()=>{gunLevel=0;gunAnimation=false;});
document.querySelector('#gun-high')!.addEventListener('click',()=>{gunLevel=1;gunAnimation=false;});
document.querySelector('#gun-animate')!.addEventListener('click',()=>{gunAnimation=!gunAnimation;});
document.querySelector('#gun-reverse')!.addEventListener('click',()=>{gunDirection*=-1;});
document.querySelector('#gun-recoil')!.addEventListener('click',()=>{gunFiredAt=performance.now();});
function paintGuns(now:number){for(const sample of samples){const m=gunMount(sample.id)!,level=gunAnimation?(Math.sin(now/1500)+1)/2:gunLevel,e=m.minElevation+(m.maxElevation-m.minElevation)*(.08+level*.75),c=sample.canvas.getContext('2d')!;c.clearRect(0,0,420,170);c.fillStyle='#69715b';c.fillRect(0,153,420,17);drawArticulatedGun(c,art.gunParts![sample.id],{id:sample.id,x:sample.id.startsWith('mortar')?210:gunDirection<0?305:115,y:CARDS[sample.id].emplacement?emplacementContact(()=>153,115,sample.id,gunDirection).y:153,hullAngle:CARDS[sample.id].emplacement?emplacementContact(()=>153,115,sample.id,gunDirection).angle:0,side:gunDirection<0?1:0,facing:gunDirection,gunFacing:gunDirection,gunElevation:e,fire:Math.max(0,.25-(now-gunFiredAt)/1000)});sample.label.textContent=CARDS[sample.id].name+' · '+Math.round(e*180/Math.PI)+'°';}}
let s:GameState,paused=true,hills=true,mode='unit',remainder=0,reported=0;const budget=new BattleFrameBudget();
function spawn(side:0|1,id:CardId,x:number){const n=s.units.length;spawnUnit(s,side,id,x);return s.units[n];}
function reset(){s=createGame(231,undefined,undefined,undefined,{weather:false});startGame(s);Object.assign(s,{units:[],wrecks:[],knownScenery:[{},{}],knownWalls:[{},{}],scenery:[],walls:[],aiIn:1e9,night:false});for(let x=0;x<s.terrain.length;x++)s.terrain[x]=s.original[x]=hills?374+Math.sin((x-700)/130)*24:374;s.terrainVersion++;for(const p of s.players)Object.assign(p,{order:'advance',hand:[],deck:[],discard:[],energy:0});
 if(mode==='scale'){for(const [id,x] of [['tank',850],['sp_howitzer_122',1140],['sp_howitzer_155',1460]] as const){const u=spawn(0,id,x);u.logisticsOrder='hold';}spawn(0,'scouts',1680);spawn(1,'infantry',1900);}
 else if(mode==='unit'){const host=spawn(0,select.value as CardId,1200);if(CARDS[host.id].fortification){host.buildUntil=0;tick(s,.05);}spawn(0,'infantry',1500);const foe=spawn(1,'infantry',1770);Object.assign(foe,{squadOrder:'watch',squadOrderX:1770,squadOrderUntil:Infinity});}
 else if(mode==='crossing'){const gun=spawn(0,'machinegun',1050);Object.assign(gun,{pose:'crouch',squadOrder:'watch',squadOrderX:gun.x,squadOrderUntil:Infinity});spawn(0,'infantry',1180);spawn(1,'infantry',1580);}
 else if(mode==='house'){spawn(0,'pickup',1100);s.scenery=createScenery(s.terrain,[{kind:'house',x:1100,seed:228}]);const observer=spawn(0,'scouts',1350),foe=spawn(1,'infantry',1400);Object.assign(observer,{squadOrder:'watch',squadOrderX:observer.x,squadOrderUntil:Infinity});Object.assign(foe,{squadOrder:'watch',squadOrderX:foe.x,squadOrderUntil:Infinity});}
 else if(mode==='house-target'){spawn(0,'pickup',1100);s.scenery=createScenery(s.terrain,[{kind:'house',x:1400,seed:228},{kind:'tree',x:1280,seed:228}]);const foe=spawn(1,'infantry',1400);Object.assign(foe,{squadOrder:'watch',squadOrderX:foe.x,squadOrderUntil:Infinity});}
 else if(mode==='mixed'){spawn(0,'pickup',1020);spawn(0,'tow_ifv',1140);spawn(1,'tow_ifv',1450);const carrier=spawn(1,'apc_transport',1550);carrier.transportReleased=true;s.scenery=createScenery(s.terrain,[{kind:'house',x:1400,seed:228},{kind:'tree',x:1290,seed:228},{kind:'tree',x:1330,seed:230}]);}
 else if(mode==='duel'){const truck=spawn(0,'pickup',1100),carrier=spawn(1,'apc_transport',1230);carrier.transportReleased=true;s.wrecks.push({id:++s.uid,cardId:'tank',side:1,x:1235,y:374,age:20,falling:false,vx:0,vy:0,angle:0,facing:-1});}
 else {const friend=spawn(0,'infantry',1100),carrier=spawn(1,'apc_transport',1370);carrier.transportReleased=true;Object.assign(carrier,{squadOrder:'watch',squadOrderX:1370,squadOrderUntil:Infinity});spawn(1,'infantry',1500);spawn(0,'pickup',920);friend.satchelLeft=0;}
 refreshVision(s);paused=true;remainder=0;reported=0;budget.reset(performance.now());}
select.onchange=()=>{mode='unit';reset();};document.querySelector('#hills')!.addEventListener('click',()=>{hills=!hills;reset();});document.querySelector('#crossing')!.addEventListener('click',()=>{mode='crossing';hills=false;reset();});document.querySelector('#duel')!.addEventListener('click',()=>{mode='duel';hills=false;reset();});document.querySelector('#scale')!.addEventListener('click',()=>{mode='scale';hills=false;reset();});document.querySelector('#house')!.addEventListener('click',()=>{mode='house';hills=false;reset();});document.querySelector('#house-target')!.addEventListener('click',()=>{mode='house-target';hills=false;reset();});document.querySelector('#mixed')!.addEventListener('click',()=>{mode='mixed';hills=false;reset();});document.querySelector('#carrier')!.addEventListener('click',()=>{mode='carrier';hills=false;reset();});document.querySelector('#reset')!.addEventListener('click',reset);document.querySelector('#pause')!.addEventListener('click',()=>{paused=!paused;budget.reset(performance.now());});document.querySelector('#step')!.addEventListener('click',()=>{paused=true;for(let i=0;i<30;i++)tick(s,1/30);reported=0;});reset();
function frame(now:number){requestAnimationFrame(frame);paintGuns(now);if(document.hidden){budget.reset(now);return;}const dt=budget.take(now,true);if(dt===null)return;const at=performance.now();if(!paused)remainder=advanceBattleFrame(s,dt,remainder);render(ctx,s,art,null,null,true,650,1024,null,true);budget.record(now,performance.now()-at);if(now-reported>.4e3){reported=now;stats.textContent=`${paused?'暂停':'交火中'} · ${s.time.toFixed(1)}秒 · ${hills?'坡地':'平地'}\n`+s.units.map(u=>`${u.side?'敌':'我'} ${CARDS[u.id].name}：${u.fortCrewUid?'固定守军 ':''}${u.pose}，射击${u.shots-u.member}次，副武器${u.secondaryShots}次，生命${u.hp.toFixed(0)}，位置${Math.round(u.x)}，弹药${u.ammo??'—'}`).join('\n');}}
requestAnimationFrame(frame);
