import '../app/globals.css';
import {createRoot} from 'react-dom/client';import {CardFace} from '../game/card-art';
import {EXPANSION_IDS_V227} from '../game/expansion-v227';
import {loadBattleArt} from '../game/art';import {createGame,startGame,spawnUnit,tick,refreshVision,CARDS,type GameState,type CardId} from '../game/engine';import {render} from '../game/render';
import {createScenery} from '../game/world';
import {advanceBattleFrame} from '../game/battle-clock';import {BattleFrameBudget} from '../game/battle-frame-budget';
const ids:CardId[]=[...EXPANSION_IDS_V227,'pickup','supply_truck','apc_transport','mlrs'];
createRoot(document.querySelector('#cards')!).render(ids.map(id=><div className="card-preview" key={id}><CardFace id={id} eager/></div>));
const select=document.getElementById('unit') as unknown as HTMLSelectElement;select.innerHTML=ids.map(id=>`<option value="${id}">${CARDS[id].name}</option>`).join('');
const canvas=document.querySelector<HTMLCanvasElement>('#view')!,ctx=canvas.getContext('2d')!,stats=document.querySelector('#stats')!,art=await loadBattleArt('greyline');
let s:GameState,paused=true,hills=true,mode='unit',remainder=0,reported=0;const budget=new BattleFrameBudget();
function spawn(side:0|1,id:CardId,x:number){const n=s.units.length;spawnUnit(s,side,id,x);return s.units[n];}
function reset(){s=createGame(228,undefined,undefined,undefined,{weather:false});startGame(s);Object.assign(s,{units:[],wrecks:[],knownScenery:[{},{}],knownWalls:[{},{}],scenery:[],walls:[],aiIn:1e9,night:false});for(let x=0;x<s.terrain.length;x++)s.terrain[x]=s.original[x]=hills?374+Math.sin((x-700)/130)*24:374;s.terrainVersion++;for(const p of s.players)Object.assign(p,{order:'advance',hand:[],deck:[],discard:[],energy:0});
 if(mode==='unit'){const host=spawn(0,select.value as CardId,1200);if(CARDS[host.id].fortification){host.buildUntil=0;tick(s,.05);}spawn(0,'infantry',1500);const foe=spawn(1,'infantry',1770);Object.assign(foe,{squadOrder:'watch',squadOrderX:1770,squadOrderUntil:Infinity});}
 else if(mode==='crossing'){const gun=spawn(0,'machinegun',1050);Object.assign(gun,{pose:'crouch',squadOrder:'watch',squadOrderX:gun.x,squadOrderUntil:Infinity});spawn(0,'infantry',1180);spawn(1,'infantry',1580);}
 else if(mode==='house'){spawn(0,'pickup',1100);s.scenery=createScenery(s.terrain,[{kind:'house',x:1100,seed:228}]);const observer=spawn(0,'scouts',1350),foe=spawn(1,'infantry',1400);Object.assign(observer,{squadOrder:'watch',squadOrderX:observer.x,squadOrderUntil:Infinity});Object.assign(foe,{squadOrder:'watch',squadOrderX:foe.x,squadOrderUntil:Infinity});}
 else if(mode==='duel'){const truck=spawn(0,'pickup',1100),carrier=spawn(1,'apc_transport',1230);carrier.transportReleased=true;s.wrecks.push({id:++s.uid,cardId:'tank',side:1,x:1235,y:374,age:20,falling:false,vx:0,vy:0,angle:0,facing:-1});}
 else {const friend=spawn(0,'infantry',1100),carrier=spawn(1,'apc_transport',1370);carrier.transportReleased=true;Object.assign(carrier,{squadOrder:'watch',squadOrderX:1370,squadOrderUntil:Infinity});spawn(1,'infantry',1500);spawn(0,'pickup',920);friend.satchelLeft=0;}
 refreshVision(s);paused=true;remainder=0;reported=0;budget.reset(performance.now());}
select.onchange=()=>{mode='unit';reset();};document.querySelector('#hills')!.addEventListener('click',()=>{hills=!hills;reset();});document.querySelector('#crossing')!.addEventListener('click',()=>{mode='crossing';hills=false;reset();});document.querySelector('#duel')!.addEventListener('click',()=>{mode='duel';hills=false;reset();});document.querySelector('#house')!.addEventListener('click',()=>{mode='house';hills=false;reset();});document.querySelector('#carrier')!.addEventListener('click',()=>{mode='carrier';hills=false;reset();});document.querySelector('#reset')!.addEventListener('click',reset);document.querySelector('#pause')!.addEventListener('click',()=>{paused=!paused;budget.reset(performance.now());});document.querySelector('#step')!.addEventListener('click',()=>{paused=true;for(let i=0;i<30;i++)tick(s,1/30);reported=0;});reset();
function frame(now:number){requestAnimationFrame(frame);if(document.hidden){budget.reset(now);return;}const dt=budget.take(now,true);if(dt===null)return;const at=performance.now();if(!paused)remainder=advanceBattleFrame(s,dt,remainder);render(ctx,s,art,null,null,true,650,1024,null,true);budget.record(now,performance.now()-at);if(now-reported>.4e3){reported=now;stats.textContent=`${paused?'暂停':'交火中'} · ${s.time.toFixed(1)}秒 · ${hills?'坡地':'平地'}\n`+s.units.map(u=>`${u.side?'敌':'我'} ${CARDS[u.id].name}：${u.fortCrewUid?'固定守军 ':''}${u.pose}，射击${u.shots-u.member}次，生命${u.hp.toFixed(0)}，位置${Math.round(u.x)}，弹药${u.ammo??'—'}`).join('\n');}}
requestAnimationFrame(frame);
