import assert from 'node:assert/strict';
import {createGame,startGame,spawnUnit,playCard,tick,setOrder,refreshVision,visibleToSide,CARDS,W,validDeck,chooseAiDeck,cardCost} from '../game/engine.ts';
import {weaponCard} from '../game/cards.ts';
import {DECK_PRESETS} from '../game/deck-presets.ts';
const metrics=[],failures=[];const dt=1/60;
function check(name,fn){try{const result=fn();metrics.push({name,...result});console.log('PASS',name,JSON.stringify(result));}catch(e){failures.push(name);console.error('FAIL',name,e.stack);}}
function arena(){const s=createGame(37);startGame(s);s.aiIn=1e6;s.terrain.fill(374);s.original.fill(374);s.scenery=[];s.walls=[];setOrder(s,0,'hold');setOrder(s,1,'hold');return s;}
function spawn(s,side,id,x){const before=s.units.length;spawnUnit(s,side,id,x);return s.units.slice(before);}
function run(s,secs,f=()=>{}){for(let i=0;i<Math.round(secs/dt);i++){tick(s,dt);f();}}
function passive(us){for(const u of us){u.cooldown=u.secondaryCooldown=1e6;}}
function card(s,side,id){const token={id,uid:++s.uid};s.players[side].hand=[token];s.players[side].energy=CARDS[id].cost;assert.equal(playCard(s,side,token.uid).ok,true);return{token,u:s.units.at(-1)};}
for(const side of [0,1]){const enemy=1-side,dir=side?-1:1,x=v=>side?W-v:v;
 check(`side${side} tanks preserve AP but leave full reload window`,()=>{const s=arena(),u=spawn(s,side,'tank',x(900))[0],v=spawn(s,enemy,'heavy_tank',x(1350))[0];passive([v]);refreshVision(s);let n=u.shots;const shots=[];run(s,10,()=>{if(u.shots>n){shots.push(s.time);n=u.shots;}});assert.ok(shots.length>=2);assert.ok(shots[1]-shots[0]>=4.79);assert.equal(CARDS.tank.penetration,390);return{shots,targetHp:v.hp};});
 check(`side${side} RPG operator actually waits5.5s while escorts retain rifles`,()=>{const s=arena(),us=spawn(s,side,'antiarmor',x(950)),v=spawn(s,enemy,'heavy_tank',x(1350))[0];passive([v]);refreshVision(s);let n=us[0].shots;const shots=[];run(s,13,()=>{if(us[0].shots>n){shots.push(s.time);n=us[0].shots;}});assert.ok(shots.length>=2);assert.ok(shots[1]-shots[0]>=5.49);assert.equal(weaponCard(us[1]).rate,1.1);return{shots};});
 for(const id of ['javelin','anti_tank_gun'])check(`side${side} ${id} saves heavy ammunition against footsoldiers and uses weak self-defence`,()=>{const s=arena(),us=spawn(s,side,id,x(1000)),vs=spawn(s,enemy,'infantry',x(1200));passive(vs);for(const u of us){u.emplaced=true;u.emplacementSetupUntil=0;}refreshVision(s);const initial=us.map(u=>u.shots);let secondary=0;run(s,4,()=>secondary=Math.max(secondary,us.reduce((n,u)=>n+u.secondaryShots,0)));assert.deepEqual(us.map(u=>u.shots),initial);assert.ok(secondary>0);return{secondary,mainShots:us.map(u=>u.shots)};});
 check(`side${side} helicopter gives six rapid shots then a real pause`,()=>{const s=arena(),u=spawn(s,side,'helicopter',x(900))[0],v=spawn(s,enemy,'heavy_tank',x(1320))[0];passive([v]);refreshVision(s);let n=0;const shots=[];run(s,3,()=>{if(u.shots>n){shots.push(s.time);n=u.shots;}});assert.ok(shots.length>=8);assert.ok(shots[1]-shots[0]<.15);assert.ok(shots[6]-shots[5]>=.59);assert.equal(u.maxHp,260);return{shots};});
 check(`side${side} FPV costs1 and expires without attacking HQ`,()=>{const s=arena(),{u}=card(s,side,'fpv_drone');assert.equal(CARDS.fpv_drone.cost,1);run(s,25);assert.equal(u.hp,0);assert.deepEqual(s.players.map(p=>p.hp),[1000,1000]);assert.ok(s.wrecks.some(w=>w.id===u.uid));return{at:u.x};});
 check(`side${side} fighter can be predeployed and stays near own front until returning with identity`,()=>{const s=arena(),{u,token}=card(s,side,'interceptor');let furthest=0;run(s,23,()=>{furthest=Math.max(furthest,side?W-u.x:u.x);assert.ok(u.moving);});assert.ok(u.hp>0);assert.ok(furthest<=905);assert.equal(u.shots,0);run(s,6);assert.equal(s.units.includes(u),false);assert.equal(s.players[side].hand.find(t=>t.uid===token.uid),token);assert.equal(cardCost(token),1);assert.equal(s.explosions,0);return{furthest,returnedAt:s.time};});
 check(`side${side} prepared fighter destroys an incoming drone using visible targets`,()=>{const s=arena(),{u}=card(s,side,'interceptor');run(s,3);const drone=spawn(s,enemy,'attack_drone',x(1700))[0];passive([drone]);refreshVision(s);run(s,6);assert.ok(drone.hp<=0);assert.ok(u.shots>=2);return{fighterHp:u.hp,shots:u.shots,droneHp:drone.hp};});
 check(`side${side} three AA guns hit and stop a fast attack sortie`,()=>{const s=arena(),guns=[1250,1420,1590].map(at=>spawn(s,side,'aa_gun',x(at))[0]);for(const g of guns){g.emplaced=true;g.emplacementSetupUntil=0;}const jet=spawn(s,enemy,'strike_jet',x(2250))[0];passive([jet]);refreshVision(s);run(s,4);assert.ok(jet.hp<=0,`jet escaped with ${jet.hp}hp`);return{jetHp:jet.hp,shots:guns.map(g=>g.shots)};});
 check(`side${side} launched guided missile freezes last target position after sight is lost`,()=>{const s=arena(),gun=spawn(s,side,'sam_vehicle',x(900))[0],target=spawn(s,enemy,'helicopter',x(1650))[0];passive([target]);refreshVision(s);let p;run(s,.4,()=>p??=s.projectiles.find(p=>p.sourceUid===gun.uid));assert.ok(p);const before={x:p.tx,y:p.ty};target.x=x(2400);s.smokes=[{side:enemy,x:x(1700),life:10}];refreshVision(s);assert.equal(visibleToSide(s,side,target),false);tick(s,dt);assert.equal(p.tx,before.x);assert.equal(p.ty,before.y);return{locked:before.x,hidden:target.x};});
}
check('all four AI presets remain legal and cover armor/air without resource cheats',()=>{for(const d of DECK_PRESETS){assert.ok(validDeck(d.cards));assert.ok(d.cards.some(id=>CARDS[id].antiAir));assert.ok(d.cards.includes('antiarmor'));assert.ok(d.cards.includes('supply'));}return{decks:DECK_PRESETS.map(d=>({name:d.name,size:d.cards.length}))};});
console.log(JSON.stringify({passed:metrics.length,failures,metrics}));if(failures.length)process.exitCode=1;
