import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,startGame,spawnUnit,tick,refreshVision,visibleToSide,snapshot,CARDS,W} from '../game/engine.ts';
import {weaponCard} from '../game/cards.ts';
import {sightRange} from '../game/world.ts';
import {vehicleTravelX,vehicleOutOfFuel} from '../game/vehicle-logistics.ts';
import {tankAimReady,TANK_ACQUIRE_S} from '../game/tank-fire-control.ts';
import {contactKind,contactMarkers} from '../game/contact-markers.ts';
import {contactSector} from './fixtures/contact-sector.mjs';
const DT=1/60,dir=side=>side?-1:1,at=(side,x)=>side?W-x:x;
function field(){const s=createGame(216,undefined,undefined,undefined,{weather:false});startGame(s);Object.assign(s,{units:[],scenery:[],walls:[],wrecks:[],knownScenery:[{},{}],aiIn:1e9,night:false});s.terrain.fill(374);s.original.fill(374);s.terrainVersion++;for(const p of s.players)Object.assign(p,{order:'advance',hand:[],deck:[],discard:[],energy:0,recon:0});return s;}
function one(s,side,id,x,extra={}){const n=s.units.length;spawnUnit(s,side,id,x);s.units.splice(n+1);const u=s.units[n];Object.assign(u,{x,y:374,pace:1,cooldown:1e9,secondaryCooldown:1e9,squadOrder:'attack',squadOrderUntil:Infinity,decisionIn:1e9,personalMorale:100,fragCooldown:1e9,...extra});return u;}
function watch(u){Object.assign(u,{squadOrder:'watch',squadOrderX:u.x,squadOrderUntil:Infinity,emplaced:true,emplacementSetupUntil:0});}
function run(s,seconds,cb){for(let i=0;i<Math.round(seconds/DT);i++){tick(s,DT);cb?.();}}
for(const side of [0,1]){
 for(const id of ['tank','light_tank','tow_ifv','scout_car','ifv','mlrs','command_vehicle'])for(const order of ['advance','resupply','hold'])test(`${side}/${id}/${order}: genuinely empty fuel cannot power any return or advance`,()=>{const s=field(),u=one(s,side,id,at(side,1100),{fuel:0,logisticsOrder:order}),x=u.x;refreshVision(s);run(s,3,()=>{assert.equal(u.x,x);assert.equal(u.fuel,0);assert(!u.moving);});assert(vehicleOutOfFuel(u));});
 test(`side ${side}: fuel runs out at the exact reachable point and local watch cannot teleport the hull home`,()=>{const s=field(),u=one(s,side,'tank',at(side,1100),{fuel:.01,squadOrder:'watch',squadOrderX:at(side,200)}),x=u.x;run(s,2);assert(Math.abs(u.x-x)<=.64000001);assert.equal(u.fuel,0);assert.equal(vehicleTravelX(u,u.x+100),u.x);});
 test(`side ${side}: ammunition exhaustion is not fuel exhaustion; delivered fuel restores a stranded vehicle`,()=>{const s=field(),u=one(s,side,'tank',at(side,1100),{ammo:0,fuel:100});run(s,1);assert(Math.abs(u.x-at(side,1100))>5);u.fuel=0;u.logisticsOrder='resupply';const x=u.x;run(s,1);assert.equal(u.x,x);s.ammoCrates=[{uid:++s.uid,side,x,stock:1800,maxStock:1800,landAt:s.time,expiresAt:100}];run(s,12);assert(u.fuel>0);assert(u.ammo>0);assert((u.x-x)*dir(side)>0,'motion only resumes after actual local delivery');});
 test(`side ${side}: main gun observes, halts, ranges and then fires; shared infantry observation reaches beyond tank vision`,()=>{const s=field(),u=one(s,side,'tank',at(side,1000),{cooldown:0}),target=one(s,1-side,'tank',at(side,1520),{hp:10000,maxHp:10000});watch(target);refreshVision(s);assert(!visibleToSide(s,side,target));run(s,.3);assert.equal(u.shots,0);const scout=one(s,side,'infantry',at(side,1430));watch(scout);refreshVision(s);assert(visibleToSide(s,side,target));const x=u.x;let launch;run(s,.9);assert.equal(u.shots,0);assert.equal(u.x,x);run(s,1,()=>{if(u.shots&&!launch)launch=s.time;});assert(launch>=.3+TANK_ACQUIRE_S);assert.equal(u.shots,1);assert.equal(u.x,x);});
 test(`side ${side}: RPG actually penetrates and seriously damages a heavy tank without harming its own rifle guards`,()=>{const s=field(),u=one(s,side,'antiarmor',at(side,1000),{cooldown:0,pose:'crouch',rifleReady:1,readyAt:-100,stillFor:10}),target=one(s,1-side,'heavy_tank',at(side,1510),{hp:10000,maxHp:10000});watch(u);watch(target);refreshVision(s);let projectile;run(s,6,()=>{projectile??=s.projectiles.find(p=>p.sourceUid===u.uid&&p.ammunition==='rocket');});assert(projectile);assert.equal(projectile.damage,100);assert.equal(projectile.armorMultiplier,2.4);assert(target.maxHp-target.hp>=180,`actual heavy armor damage ${target.maxHp-target.hp}`);assert.equal(weaponCard({id:'antiarmor',member:1}).damage,3);});
 test(`side ${side}: last observed troop type and location remain frozen under hidden motion and jump on reacquisition`,()=>{const {s,u,e,hideInCrater}=contactSector(side);const original=structuredClone(s.groundContacts[side][0]);assert.equal(original.kind,'infantry');assert.equal(original.id,'infantry');hideInCrater();e.x+=dir(side)*700;e.y=374;refreshVision(s);const stored=snapshot(s,side).contacts.find(c=>c.uid===e.uid);assert.equal(stored.x,original.x);assert.equal(stored.y,original.y);assert.equal(stored.kind,'infantry');assert(!snapshot(s,1-side).contacts.some(c=>c.uid===e.uid));s.terrain.fill(374);s.terrainVersion++;e.x=u.x+dir(side)*170;e.y=374;s.time+=1;refreshVision(s);assert.equal(snapshot(s,side).contacts.find(c=>c.uid===e.uid).x,e.x);});
 test(`side ${side}: infantry does not walk back into an uncleared armored sight boundary after escaping`,()=>{const s=field(),u=one(s,side,'infantry',at(side,1100),{decisionIn:0,pose:'idle'}),tank=one(s,1-side,'tank',at(side,1480));watch(tank);refreshVision(s);assert(visibleToSide(s,side,tank));let farthest=u.x,forward=0;run(s,20,()=>{if(s.time<5)farthest=u.x;else forward=Math.max(forward,(u.x-farthest)*dir(side));});assert((at(side,1100)-u.x)*dir(side)>200);assert(forward<15,`no repeated forward probe during fresh lost contact: ${forward}`);assert(s.groundContacts[side].some(c=>c.uid===tank.uid));});
}
test('tank gun range exceeds own observation and infantry observation exceeds weapon range',()=>{for(const id of ['tank','light_tank','heavy_tank'])assert(CARDS[id].range>sightRange({id,squadOrder:'attack'}));for(const id of ['infantry','antiarmor','rocket','javelin','scouts'])assert(sightRange({id,squadOrder:'attack',member:0})>weaponCard({id,member:0}).range);});
test('tank ranging overlaps loading, resets only for new target or actual motion',()=>{const u={id:'tank',x:1000};assert(!tankAimReady(u,0,'1',1500,330));for(let t=.1;t<1.2;t+=.1)assert(!tankAimReady(u,t,'1',1500+t*5,330));assert(tankAimReady(u,1.21,'1',1505,330));assert(tankAimReady(u,1.4,'1',1510,330));u.tankMovedAt=1.5;assert(!tankAimReady(u,1.5,'1',1510,330));const deadline=u.tankAim.readyAt;assert(tankAimReady(u,deadline,'1',1510,330));assert(!tankAimReady(u,deadline+.1,'2',1510,330));});
test('map icons distinguish tanks and group only last observed infantry coordinates',()=>{assert.equal(contactKind('tank'),'tank');assert.equal(contactKind('heavy_tank'),'tank');assert.equal(contactKind('infantry'),'infantry');const reports=[{uid:1,side:1,x:1000,y:374,seenAt:0,kind:'infantry',squad:1},{uid:2,side:1,x:1020,y:374,seenAt:0,kind:'infantry',squad:1},{uid:3,side:1,x:1200,y:374,seenAt:0,kind:'tank',squad:1}];const marks=contactMarkers(reports);assert.equal(marks.length,2);assert.equal(marks[0].x,1010);assert.equal(marks[1].kind,'tank');});
