import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,startGame,spawnUnit,tick,refreshVision,CARDS,W} from '../game/engine.ts';
import {selectUnitGroup,setSquadOrder,ordersForUnit,automaticFireSupport} from '../game/squad-orders.ts';
import {issueLogisticsOrder} from '../game/logistics-orders.ts';
const DT=1/60,dir=side=>side?-1:1,at=(side,x)=>side?W-x:x;
function arena(){const s=createGame(217,undefined,undefined,undefined,{weather:false});startGame(s);Object.assign(s,{units:[],scenery:[],walls:[],wrecks:[],knownScenery:[{},{}],aiIn:1e9,night:false});s.terrain.fill(374);s.original.fill(374);s.terrainVersion++;for(const p of s.players)Object.assign(p,{order:'advance',hand:[],deck:[],discard:[],energy:0});return s;}
function one(s,side,id,x,extra={}){const n=s.units.length;spawnUnit(s,side,id,x);s.units.splice(n+1);const u=s.units[n];Object.assign(u,{x,y:374,pace:1,cooldown:1e9,secondaryCooldown:1e9,decisionIn:1e9,personalMorale:100,fragCooldown:1e9,...extra});return u;}
function run(s,sec){for(let i=0;i<Math.round(sec/DT);i++)tick(s,DT);}
function field(side,id){const s=arena(),gun=one(s,side,id,at(side,900)),front=one(s,side,'infantry',at(side,1500));front.squadOrder='watch';front.squadOrderX=front.x;refreshVision(s);return{s,gun,front};}
const ids=['artillery','barrage','field_gun','siege_gun','anti_tank_gun','aa_gun','mlrs','mortar_carrier'].filter(id=>CARDS[id]);
for(const side of [0,1])for(const id of ids){
 test(`${side}/${id}: repeated inspection and closing the fan cannot cancel real automatic following`,()=>{const {s,gun}=field(side,id);run(s,.3);const before=gun.x,task=gun.squadOrder;for(let n=0;n<3;n++){assert(selectUnitGroup(s,side,gun.squad).ok);assert.equal(gun.squadOrder,task);run(s,1);}assert((gun.x-before)*dir(side)>20);assert(ordersForUnit(id).some(o=>o.id==='escort'&&o.label==='自动跟随'));});
 test(`${side}/${id}: an explicit watch persists through selection, auto-follow deliberately releases it`,()=>{const {s,gun}=field(side,id);assert(setSquadOrder(s,side,gun.squad,'watch').ok);const x=gun.x;run(s,3);assert.equal(gun.x,x);assert(selectUnitGroup(s,side,gun.squad).ok);assert.equal(gun.squadOrder,'watch');run(s,2);assert.equal(gun.x,x);assert(setSquadOrder(s,side,gun.squad,'escort').ok);run(s,10);assert((gun.x-x)*dir(side)>20);assert.equal(gun.squadOrder,undefined);});
 if(CARDS[id].emplacement)for(const order of ['attack','retreat'])test(`${side}/${id}/${order}: one crew-towed bound finishes and returns to auto without another click`,()=>{const {s,gun,front}=field(side,id);assert(setSquadOrder(s,side,gun.squad,order).ok);const x=gun.x,goal=gun.squadOrderX;run(s,order==='attack'?11:17);assert.equal(gun.squadOrder,undefined);assert(Math.abs(gun.x-goal)<1.01,'the actual assigned position was reached');assert((gun.x-x)*dir(side)*(order==='attack'?1:-1)>235);front.x=at(side,2300);front.squadOrderX=front.x;refreshVision(s);const done=gun.x;run(s,10);assert((gun.x-done)*dir(side)>20,'continues following the newly advanced screen');});
}
for(const side of [0,1])test(`side ${side}: viewing a gun on its supply return preserves the chosen resupply task`,()=>{const {s,gun}=field(side,'artillery');gun.ammo=1;if(side===0)assert(issueLogisticsOrder(s,gun.uid,'resupply'));run(s,1);const state=gun.resupplyState,goal=gun.resupplyGoal,x=gun.x;assert(selectUnitGroup(s,side,gun.squad).ok);assert.equal(gun.resupplyState,state);assert.equal(gun.resupplyGoal,goal);run(s,2);assert((gun.x-x)*dir(side)<-10);});
for(const side of [0,1])test(`side ${side}: a march clipped by a known enemy line releases into legal fire instead of endlessly pushing`,()=>{const {s,gun}=field(side,'anti_tank_gun');gun.x=at(side,1100);gun.cooldown=0;const foe=one(s,1-side,'tank',at(side,1260),{fuel:0,hp:10000,maxHp:10000,squadOrder:'watch',squadOrderX:at(side,1260)});refreshVision(s);assert(setSquadOrder(s,side,gun.squad,'attack').ok);run(s,4);assert.equal(gun.squadOrder,undefined);assert(gun.shots>0);assert(foe.hp<10000);});
test('selection remains an explicit stop for regular infantry and vehicles',()=>{for(const id of ['infantry','tank']){assert(!automaticFireSupport(id));const{s,gun}=field(0,id);assert(selectUnitGroup(s,0,gun.squad).ok);assert.equal(gun.squadOrder,'watch');const x=gun.x;run(s,3);assert.equal(gun.x,x);}});

for(const side of [0,1])for(const id of ['mlrs','mortar_carrier'])test(`${side}/${id}: completing a manual withdrawal restores the rear-line follow task`,()=>{const {s,gun,front}=field(side,id);assert(setSquadOrder(s,side,gun.squad,'retreat').ok);const x=gun.x;for(let n=0;n<1200&&gun.squadOrder==='retreat';n++)tick(s,DT);assert.equal(gun.squadOrder,undefined);assert((gun.x-x)*dir(side)<-200);front.x=at(side,2300);front.squadOrderX=front.x;refreshVision(s);const done=gun.x;run(s,12);assert((gun.x-done)*dir(side)>20);});
