import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,startGame,spawnUnit,playCard,tick,refreshVision,visibleToSide,cardCost,snapshot,toggleRadar,activeRadarTarget,hostileLanding,W,ARTILLERY} from '../game/engine.ts';
import {CARDS,DECK,DECK_SIZE,validDeck,chooseAiDeck,copyLimit} from '../game/cards.ts';
import {DECK_PRESETS} from '../game/deck-presets.ts';
import {pointVisible,airGroundSight} from '../game/world.ts';
import {updateEconomy,applyEconomy} from '../game/economy.ts';
import {loadDeckStore,DECKS_STORAGE} from '../game/decks-store.ts';
import {starterState,validDeckWithCollection} from '../game/collection.ts';
function arena(seed=233){const s=createGame(seed,undefined,undefined,undefined,{weather:false});startGame(s);Object.assign(s,{units:[],scenery:[],walls:[],wrecks:[],aiIn:1e9,night:false});s.terrain.fill(374);s.original.fill(374);s.terrainVersion++;for(const p of s.players)Object.assign(p,{order:'hold',hand:[],deck:[],discard:[],energy:20});return s;}
function one(s,side,id,x,patch={}){const n=s.units.length;spawnUnit(s,side,id,x);const u=s.units[n];s.units.splice(n+1);Object.assign(u,{x,y:CARDS[id].air?210:374,cooldown:1e9,secondaryCooldown:1e9,fragCooldown:1e9,readyAt:-10,lane:0,transportReleased:true,logisticsOrder:'hold',...patch});return u;}
function token(s,side,id){const t={id,uid:++s.uid};s.players[side].hand.push(t);return t;}
function run(s,n){for(let i=0;i<n*60;i++)tick(s,1/60);}
test('25-card formations and 25/30/35-card opponents, including custom campaign loadouts',()=>{assert.equal(DECK_SIZE,25);assert(validDeck(DECK));assert(validDeckWithCollection(DECK,starterState()));for(const p of DECK_PRESETS)assert(validDeck(p.cards),p.name);for(const [difficulty,size]of [['standard',25],['veteran',30],['elite',35]])for(let seed=1;seed<25;seed++){assert(validDeck(chooseAiDeck(seed,difficulty),size));const s=createGame(seed,DECK,DECK,undefined,{difficulty});assert.equal(s.players[0].loadout.length,25);assert.equal(s.players[1].loadout.length,size);assert(!s.players[1].loadout.includes('mine_clearer'));}});
test('requested costs and removal from legal deck',()=>{for(const [id,cost]of Object.entries({anti_radiation_shell:3,stealth_bomber:10,heavy_tank:12,command_vehicle:3,ifv:4,tow_ifv:4,tank:8,foraged_supplies:2,rally:0}))assert.equal(CARDS[id].cost,cost,id);assert.equal(copyLimit('mine_clearer'),0);assert(!DECK.includes('mine_clearer'));assert.equal(CARDS.anti_radiation_shell.type,'skill');});
test('legacy saved 20-card deck preserves existing cards and adds five owned legal cards',()=>{const old=DECK.slice(0,20);const data=new Map([[DECKS_STORAGE,JSON.stringify({decks:[{id:'old',name:'旧编队',cards:old}],activeId:'old'})]]);globalThis.localStorage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)};const store=loadDeckStore(starterState());assert.equal(store.decks[0].cards.length,25);assert.deepEqual(store.decks[0].cards.slice(0,20),old);});
for(const side of [0,1]){
 test(`side ${side}: hidden powered radar dies; off radar survives; no target consumes nothing`,()=>{const s=arena(),p=s.players[side],sam=one(s,1-side,'sam_vehicle',side?1000:2800),off=one(s,1-side,'sam_vehicle',side?1050:2850);toggleRadar(s,off.uid);refreshVision(s);assert(!visibleToSide(s,side,sam));const h=token(s,side,'anti_radiation_shell'),before=p.energy;assert.equal(activeRadarTarget(s,side)?.uid,sam.uid);assert(playCard(s,side,h.uid).ok);assert.equal(sam.hp,0);assert(sam.destroyed);assert(off.hp>0);assert.equal(p.energy,before-3);assert(s.wrecks.some(w=>w.id===sam.uid));const again=token(s,side,'anti_radiation_shell'),energy=p.energy;assert(!playCard(s,side,again.uid).ok);assert.equal(p.energy,energy);assert(p.hand.includes(again));});
 test(`side ${side}: jammer covers friendly front line for exactly eight seconds, base and card play remain available`,()=>{const s=arena(),victim=1-side,own=one(s,victim,'infantry',1800),foe=one(s,side,'infantry',1950);refreshVision(s);assert(pointVisible(s,victim,own.x,own.y-20));assert(visibleToSide(s,victim,foe));assert(playCard(s,side,token(s,side,'jam').uid).ok);assert(!pointVisible(s,victim,own.x,own.y-20));assert(!visibleToSide(s,victim,foe));assert(!snapshot(s,victim).units.some(u=>u.uid===own.uid));assert(pointVisible(s,victim,victim?W-70:70,350));assert.equal(snapshot(s,victim).contacts.length,0);assert(playCard(s,victim,token(s,victim,'rally').uid).ok);assert.equal(s.players[victim].lockoutUntil??0,0);run(s,7.9);assert(!pointVisible(s,victim,own.x,own.y-20));run(s,.2);assert(pointVisible(s,victim,own.x,own.y-20));});
 test(`side ${side}: forage returns two discard tokens to draw pile, without self-return or drawing`,()=>{const s=arena(),p=s.players[side],a={id:'tank',uid:++s.uid},b={id:'ifv',uid:++s.uid};p.discard=[a,b];const h=token(s,side,'foraged_supplies');assert(playCard(s,side,h.uid).ok);assert.equal(p.hand.length,0);assert.deepEqual(new Set(p.deck),new Set([a,b]));assert.deepEqual(p.discard,[h]);});
 test(`side ${side}: salvage can retrieve a twelve-cost heavy tank`,()=>{const s=arena(),p=s.players[side],heavy={id:'heavy_tank',uid:++s.uid};p.discard=[heavy];assert(playCard(s,side,token(s,side,'battlefield_salvage').uid).ok);assert(p.hand.includes(heavy));});
 test(`side ${side}: occupied landing aborts before first soldier, actual flight home returns same token at one cost`,()=>{const s=arena(),x=1800,foe=one(s,1-side,'infantry',x),h=token(s,side,'air_assault');assert(playCard(s,side,h.uid,x).ok);const u=s.units.find(u=>u.id==='air_assault');u.cooldown=1e9;assert(!s.players[side].discard.includes(h));let aborted=false;for(let i=0;i<14*60;i++){tick(s,1/60);if(u.airlift.aborted){aborted=true;assert(!s.units.some(v=>v.side===side&&v.id==='paratroopers'));if(u.hp>0)assert(!s.players[side].hand.includes(h));}}assert(aborted);assert.equal(u.airlift.dropped,0);assert.equal(u.hp,0);assert(s.players[side].hand.includes(h));assert.equal(cardCost(h),1);assert.equal(s.players[side].hand.filter(t=>t.uid===h.uid).length,1);assert(!s.players[side].discard.includes(h));});
 test(`side ${side}: aborted insertion returns at one cost even when hand fills during flight`,()=>{const s=arena(),h=token(s,side,'air_assault');one(s,1-side,'infantry',1800);assert(playCard(s,side,h.uid,1800).ok);for(let i=0;i<6;i++)token(s,side,'rally');run(s,16);assert.equal(s.players[side].hand.length,7);assert(s.players[side].hand.includes(h));assert.equal(cardCost(h),1);assert(!s.players[side].discard.includes(h));});
 test(`side ${side}: clear airlift deploys five elite troops and consumes original token on return`,()=>{const s=arena(),h=token(s,side,'air_assault');assert(playCard(s,side,h.uid,1700).ok);run(s,22);const cargo=s.units.filter(u=>u.id==='paratroopers'&&u.side===side);assert.equal(cargo.length,5);assert(cargo.every(u=>u.training==='elite'));assert(!s.players[side].hand.includes(h));assert(s.players[side].discard.includes(h));assert.equal(h.returnedOnce,false);});
 test(`side ${side}: hidden enemy does not leak into landing decision`,()=>{const s=arena(),u=one(s,side,'air_assault',500),foe=one(s,1-side,'infantry',2800);refreshVision(s);assert(!visibleToSide(s,side,foe));assert(!hostileLanding(s,u,2800));});
 test(`side ${side}: aborted helicopter shot down before reaching home does not refund card`,()=>{const s=arena(),h=token(s,side,'air_assault');playCard(s,side,h.uid,1800);const u=s.units.find(u=>u.id==='air_assault');one(s,1-side,'infantry',1800);run(s,6);assert(u.airlift.aborted);s.projectiles.push({uid:++s.uid,sourceUid:99999,targetUid:u.uid,side:1-side,base:null,startX:u.x-10,startY:u.y-20,x:u.x-10,y:u.y-20,tx:u.x,ty:u.y-20,total:.01,life:.01,arc:0,damage:1000,radius:10,ammunition:'cannon'});run(s,.2);assert(!s.players[side].hand.includes(h));assert(s.players[side].discard.includes(h));});
}
test('overdraft freezes natural income for forty seconds, fractional expiry earns only eligible time',()=>{const s=arena(),p=s.players[0];p.energy=0;applyEconomy(p,'overdraft',0);assert.equal(p.energy,7);s.time=39.99;updateEconomy(s,0,1);assert.equal(p.energy,7);s.time=40.01;updateEconomy(s,0,.02);assert(Math.abs(p.energy-(7+.01/5.5))<1e-9);s.time=41.01;updateEconomy(s,0,1);assert(Math.abs(p.energy-(7+1.01/5.5))<1e-9);});
test('one-off naval strike has meaningful heavy damage and all existing off-map strike costs fall',()=>{assert.equal(ARTILLERY.naval.damage,300);assert.equal(ARTILLERY.naval.armorMultiplier,2);assert.equal(ARTILLERY.naval.baseScale,.6);assert(CARDS.naval_gunfire.cost<5);});
test('actual quiet wheel, track, walking and towing motion retain hierarchy',()=>{const speeds=[];for(const id of ['pickup','sp_howitzer_122','infantry','howitzer_155']){const s=arena(),u=one(s,0,id,900,{logisticsOrder:'advance',squadOrder:'attack',squadOrderX:1800,squadOrderUntil:Infinity});one(s,0,'infantry',2200,{logisticsOrder:'hold'});s.players[0].order='advance';run(s,4);speeds.push((u.x-900)/4);}assert(speeds[0]>speeds[1]&&speeds[1]>speeds[2]&&speeds[2]>speeds[3],JSON.stringify(speeds));});
test('stealth bomber cannot reveal ground; distant radar detection resumes only while exposed',()=>{const s=arena(),radar=one(s,0,'sam_vehicle',900),plane=one(s,1,'stealth_bomber',1700);refreshVision(s);assert.equal(airGroundSight(plane),0);assert(!visibleToSide(s,0,plane));plane.exposedUntil=s.time+4;refreshVision(s);assert(visibleToSide(s,0,plane));plane.exposedUntil=0;plane.x=1100;refreshVision(s);assert(visibleToSide(s,0,plane));});
test('off radar cannot fire, switching on restores real SAM launches',()=>{const s=arena(),radar=one(s,0,'sam_vehicle',1000,{cooldown:0}),plane=one(s,1,'helicopter',1300);toggleRadar(s,radar.uid);run(s,2);assert.equal(radar.shots,0);toggleRadar(s,radar.uid);run(s,2);assert(radar.shots>0);});
test('active protection intercepts real incoming RPG/TOW projectiles at specified probabilities',()=>{const s=arena(335),tank=one(s,0,'heavy_tank',1400),tow=one(s,1,'tow_ifv',1700);let counts=[];for(const guided of [false,true]){let stopped=0;for(let i=0;i<1500;i++){tank.apsReadyAt=0;s.projectiles=[{uid:++s.uid,sourceUid:tow.uid,targetUid:tank.uid,side:1,base:null,startX:1460,startY:342,x:1460,y:342,tx:1400,ty:342,damage:0,radius:0,arc:0,total:1,life:1,ammunition:'rocket',guided,speed:100}];tick(s,.01);if(!s.projectiles.length)stopped++;}counts.push(stopped/1500);}assert(counts[0]>.86&&counts[0]<.94,JSON.stringify(counts));assert(counts[1]>.44&&counts[1]<.56,JSON.stringify(counts));});
